# Imports and Definitions

In [ ]:
import pandas as pd
import numpy as np
import math

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
dataset_path = "/content/drive/MyDrive/TCC - Identificação do Perfil de Pessoas com TOC no Brasil/Dados/dataset_random.csv"
dataset = pd.read_csv(dataset_path, delimiter=",")

In [ ]:
dataset

,Unnamed: 0,V0001,V0024,UPA_PNS,V0006_PNS,V0015,V0020,V0022,V0026,V0031,...,VDF002,VDF003,VDF004,VDL001,VDM001,VDP001,VDR001,VDDATA,toc,person_key
0,0,11,1110011,110003808,2,1,2019,1,1,1,...,2400.0,2400.0,5.0,NaN,4.0,NaN,NaN,20210825,Não,11_1110011_110003808_2_1
1,1,11,1110011,110003808,7,1,2019,3,1,1,...,250.0,83.0,1.0,NaN,NaN,NaN,5.0,20210825,Não,11_1110011_110003808_7_1
2,2,11,1110011,110007557,7,1,2019,1,1,1,...,13700.0,13700.0,7.0,NaN,1.0,NaN,NaN,20210825,Não,11_1110011_110007557_7_1
3,3,11,1110011,110008644,4,1,2019,2,1,1,...,4000.0,2000.0,5.0,NaN,1.0,NaN,NaN,20210825,Não,11_1110011_110008644_4_2
4,4,11,1110011,110008644,15,1,2019,2,1,1,...,1996.0,998.0,3.0,NaN,NaN,NaN,1.0,20210825,Não,11_1110011_110008644_15_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4787,293,53,5310211,530000135,7,1,2019,3,1,1,...,2000.0,667.0,3.0,NaN,NaN,NaN,6.0,20210825,Sim,53_5310211_530000135_7_1
4788,294,53,5310211,530037460,2,1,2019,3,1,1,...,9000.0,3000.0,6.0,NaN,4.0,NaN,NaN,20210825,Sim,53_5310211_530037460_2_1
4789,295,53,5310211,530042333,3,1,2019,1,1,1,...,1500.0,1500.0,4.0,NaN,NaN,NaN,NaN,20210825,Sim,53_5310211_530042333_3_1
4790,296,53,5310212,530029819,15,1,2019,1,1,1,...,1497.0,1497.0,4.0,NaN,2.0,1.0,NaN,20210825,Sim,53_5310212_530029819_15_1
4791,297,53,5310212,530033471,9,1,2019,4,1,1,...,7998.0,2000.0,5.0,NaN,3.0,1.0,1.0,20210825,Sim,53_5310212_530033471_9_2

# Variaveis Socioeconomicas

## informações pessoais

In [ ]:
novo_df = pd.DataFrame(dataset[['person_key', 'C006', 'C008', 'C009', 'C011']])

In [ ]:
novo_df = novo_df.rename(columns={'C006': 'sexo', 'C008': 'idade', 'C009':'cor_raca', 'C011':'estado_civil'})

In [ ]:
novo_df = pd.merge(novo_df, dataset[['person_key', 'toc']], on='person_key', how='left')

In [ ]:
novo_df

                     person_key  sexo  idade  cor_raca  estado_civil  toc
0      11_1110011_110003808_2_1     2     55         2             4  Não
1      11_1110011_110003808_7_1     2     30         1             1  Não
2      11_1110011_110007557_7_1     2     65         1             4  Não
3      11_1110011_110008644_4_2     1     23         1             4  Não
4     11_1110011_110008644_15_1     2     77         4             2  Não
...                         ...   ...    ...       ...           ...  ...
4787   53_5310211_530000135_7_1     2     37         4             4  Sim
4788   53_5310211_530037460_2_1     2     52         4             1  Sim
4789   53_5310211_530042333_3_1     2     56         4             2  Sim
4790  53_5310212_530029819_15_1     1     42         2             4  Sim
4791   53_5310212_530033471_9_2     2     45         2             4  Sim

[4792 rows x 6 columns]

In [ ]:
# Assuming df is defined somewhere in your code before this point

sexo = {"1": "Homem", "2": "Mulher"}

cor_raca = {
    "1": "Branca",
    "2": "Preta",
    "3": "Amarela",
    "4": "Parda",
    "5": "Indígena"
}

estado_civil = {
    "1": "Casado(a)",
    "2": "Divorciado(a) ou desquitado(a) ou separado(a) judicialmente",
    "3": "Viúvo(a)",
    "4": "Solteiro(a)"
}

columns = {'sexo': sexo, 'cor_raca': cor_raca, 'estado_civil': estado_civil}

In [ ]:
def replace_key(code, value_dict):
    return value_dict.get(str(code), code)

for column, value_dict in columns.items():
    novo_df[column] = novo_df[column].apply(replace_key, args=(value_dict, ))

In [ ]:
novo_df['idade_int'] = novo_df['idade'].astype(int)

In [ ]:
novo_df['idade']

0       55
1       30
2       65
3       23
4       77
        ..
4787    37
4788    52
4789    56
4790    42
4791    45
Name: idade, Length: 4792, dtype: int64

In [ ]:
novo_df.loc[
    (novo_df['idade_int'] >= 18) & (novo_df['idade_int'] < 25), 'idade'
] = 'Jovem Adulto'

novo_df.loc[
    (novo_df['idade_int'] >= 25) & (novo_df['idade_int'] < 40), 'idade'
] = 'Adulto'

novo_df.loc[
    (novo_df['idade_int'] >= 40) & (novo_df['idade_int'] < 60), 'idade'
] = 'Meia Idade'

novo_df.loc[
    (novo_df['idade_int'] >= 60) & (novo_df['idade_int'] < 80), 'idade'
] = 'Idade Madura'

novo_df.loc[
    (novo_df['idade_int'] >= 80) , 'idade'
] = 'Idoso'

In [ ]:
novo_df.drop(columns=['idade_int'], inplace=True)

In [ ]:
novo_df

,person_key,sexo,idade,cor_raca,estado_civil,toc
0,11_1110011_110003808_2_1,Mulher,Meia Idade,Preta,Solteiro(a),Não
1,11_1110011_110003808_7_1,Mulher,Adulto,Branca,Casado(a),Não
2,11_1110011_110007557_7_1,Mulher,Idade Madura,Branca,Solteiro(a),Não
3,11_1110011_110008644_4_2,Homem,Jovem Adulto,Branca,Solteiro(a),Não
4,11_1110011_110008644_15_1,Mulher,Idade Madura,Parda,Divorciado(a) ou desquitado(a) ou separado(a) ...,Não
...,...,...,...,...,...,...
4787,53_5310211_530000135_7_1,Mulher,Adulto,Parda,Solteiro(a),Sim
4788,53_5310211_530037460_2_1,Mulher,Meia Idade,Parda,Casado(a),Sim
4789,53_5310211_530042333_3_1,Mulher,Meia Idade,Parda,Divorciado(a) ou desquitado(a) ou separado(a) ...,Sim
4790,53_5310212_530029819_15_1,Homem,Meia Idade,Preta,Solteiro(a),Sim
4791,53_5310212_530033471_9_2,Mulher,Meia Idade,Preta,Solteiro(a),Sim

## Violencias

In [ ]:
# violencias = {
#     "1": "SIM_Frequência_Quem_Onde",
#     "2": "Não"
# }

In [ ]:
v_psi = ['V00201','V00202','V00203','V00204','V00205']
v_fis = ["V01401","V01402","V01403","V01404","V01405"]
v_sex = ["V02701","V02702","V02801","V02802"]

In [ ]:
violencias = {
    "violencia_psicologica": v_psi,
    "violencia_fisica": v_fis,
    "violencia_sexual": v_sex
}

In [ ]:
def check_row(row, yes, no):
    if any(val in yes for val in row):
      return 'Sim'  # You can return any value you want here
    else:
      if any(val in no for val in row):
        return 'Não'  # You can return any value you want here
      else: return 'Não Aplicável'

def check_and_create_status(column_name, column_keys, value_yes, value_no):
    # Check if all values in specified columns are equal to 1

    df = dataset[['person_key'] + (column_keys)].copy()
    df[column_name] = df.apply(check_row, args=(value_yes, value_no), axis=1)

    # yes = df[column_keys].eq(value_yes).all(axis=1) | df[column_keys].isna()
    # no = df[column_keys].eq(value_no).any(axis=1) | df[column_keys].isna()
    # nao_aplicavel = df[column_keys].isna().all(axis=1)

    # df.loc[yes, column_name] = 'Sim'
    # df.loc[no, column_name] = 'Não'
    # df.loc[nao_aplicavel, column_name] = 'Não Aplicável'

    return df

In [ ]:
# Create the new column 'status'
for column, value_dict in violencias.items():
    result_df = check_and_create_status(column, value_dict, [1.0], [2.0])
    novo_df = pd.merge(novo_df, result_df[['person_key', column]], on='person_key', how='left')

In [ ]:
novo_df

,person_key,sexo,idade,cor_raca,estado_civil,toc,violencia_psicologica,violencia_fisica,violencia_sexual
0,11_1110011_110003808_2_1,Mulher,Meia Idade,Preta,Solteiro(a),Não,Não,Não,Não
1,11_1110011_110003808_7_1,Mulher,Adulto,Branca,Casado(a),Não,Não,Não,Não
2,11_1110011_110007557_7_1,Mulher,Idade Madura,Branca,Solteiro(a),Não,Não,Não,Não
3,11_1110011_110008644_4_2,Homem,Jovem Adulto,Branca,Solteiro(a),Não,Não,Não,Não
4,11_1110011_110008644_15_1,Mulher,Idade Madura,Parda,Divorciado(a) ou desquitado(a) ou separado(a) ...,Não,Não,Não,Não
...,...,...,...,...,...,...,...,...,...
4787,53_5310211_530000135_7_1,Mulher,Adulto,Parda,Solteiro(a),Sim,Não,Não,Sim
4788,53_5310211_530037460_2_1,Mulher,Meia Idade,Parda,Casado(a),Sim,Não,Não,Não
4789,53_5310211_530042333_3_1,Mulher,Meia Idade,Parda,Divorciado(a) ou desquitado(a) ou separado(a) ...,Sim,Não,Não,Não
4790,53_5310212_530029819_15_1,Homem,Meia Idade,Preta,Solteiro(a),Sim,Sim,Não,Não
4791,53_5310212_530033471_9_2,Mulher,Meia Idade,Preta,Solteiro(a),Sim,Sim,Sim,Sim

In [ ]:
print(novo_df['violencia_psicologica'].value_counts(dropna=False))
print(novo_df['violencia_fisica'].value_counts(dropna=False))
print(novo_df['violencia_sexual'].value_counts(dropna=False))

violencia_psicologica
Não    3208
Sim    1584
Name: count, dtype: int64
violencia_fisica
Não    4381
Sim     411
Name: count, dtype: int64
violencia_sexual
Não    4034
Sim     758
Name: count, dtype: int64

In [ ]:
#psi,fis,sex
frequencia = ['V003', 'V015', 'V029']
relacionamento = ['V006', 'V018', 'V032']
lugar = ['V007', 'V019', 'V033']

In [ ]:
frequency_groups = {
    "1": "MuitasVezes",
    "2": "AlgumasVezes",
    "3": "UmaVez"
}

In [ ]:
relationship_groups = {
    "1": "Relacionamento Romantico",
    "2": "Relacionamento Romantico",
    "3": "Relacionamento Romantico",
    "4": "Familia",
    "5": "Familia",
    "6": "Familia",
    "7": "Familia",
    "8": "Amigo ou Vizinho",
    "9": "Trabalho",
    "10": "Trabalho",
    "11": "Outro",
    "12": "Outro",
    "13": "Outro"
}

In [ ]:
location_groups = {
    "1": "Residencia",
    "2": "Trabalho",
    "3": "EstabelecimentoEnsino",
    "4": "BarRestaurante",
    "5": "LocalPublico",
    "6": "Outro",
    "7": "Outro"
}

In [ ]:
# for index, row in novo_df.iterrows():
#   for i, key in enumerate(['violencia_psicologica', 'violencia_fisica', 'violencia_sexual']):
#     if row[key] == 'Sim':

#         person_key = row['person_key']
#         # f = dataset.loc[dataset['person_key'] == person_key, frequencia[i]].values[0]
#         r = dataset.loc[dataset['person_key'] == person_key, relacionamento[i]].values[0]
#         # l = dataset.loc[dataset['person_key'] == person_key, lugar[i]].values[0]

#         if (str(r) != 'nan'): # (str(f) != 'nan') and and (str(l) != 'nan'):
#           # frequencia_value = frequency_groups[str(int(f))]
#           relacionamento_value = relationship_groups[str(int(r))]
#           # lugar_value = location_groups[str(int(l))]
#           novo_df.at[index, key] = relacionamento_value # + '_' + lugar_value + '_' + frequencia_value
#         # else:
#         #   novo_df.at[index, key] = 'Não Aplicável'

In [ ]:
novo_df

,person_key,sexo,idade,cor_raca,estado_civil,toc,violencia_psicologica,violencia_fisica,violencia_sexual
0,11_1110011_110003808_2_1,Mulher,Meia Idade,Preta,Solteiro(a),Não,Não,Não,Não
1,11_1110011_110003808_7_1,Mulher,Adulto,Branca,Casado(a),Não,Não,Não,Não
2,11_1110011_110007557_7_1,Mulher,Idade Madura,Branca,Solteiro(a),Não,Não,Não,Não
3,11_1110011_110008644_4_2,Homem,Jovem Adulto,Branca,Solteiro(a),Não,Não,Não,Não
4,11_1110011_110008644_15_1,Mulher,Idade Madura,Parda,Divorciado(a) ou desquitado(a) ou separado(a) ...,Não,Não,Não,Não
...,...,...,...,...,...,...,...,...,...
4787,53_5310211_530000135_7_1,Mulher,Adulto,Parda,Solteiro(a),Sim,Não,Não,Sim
4788,53_5310211_530037460_2_1,Mulher,Meia Idade,Parda,Casado(a),Sim,Não,Não,Não
4789,53_5310211_530042333_3_1,Mulher,Meia Idade,Parda,Divorciado(a) ou desquitado(a) ou separado(a) ...,Sim,Não,Não,Não
4790,53_5310212_530029819_15_1,Homem,Meia Idade,Preta,Solteiro(a),Sim,Sim,Não,Não
4791,53_5310212_530033471_9_2,Mulher,Meia Idade,Preta,Solteiro(a),Sim,Sim,Sim,Sim

In [ ]:
print(novo_df['violencia_psicologica'].value_counts(dropna=False))
print()
print(novo_df['violencia_fisica'].value_counts(dropna=False))
print()
print(novo_df['violencia_sexual'].value_counts(dropna=False))

violencia_psicologica
Não    3208
Sim    1584
Name: count, dtype: int64

violencia_fisica
Não    4381
Sim     411
Name: count, dtype: int64

violencia_sexual
Não    4034
Sim     758
Name: count, dtype: int64

In [ ]:
# Filter novo_df for person_keys where 'violencia_sexual' is 'Sim'
violencias = ['violencia_psicologica', 'violencia_fisica', 'violencia_sexual']
frequencia = ['V003', 'V015', 'V029']
relacionamento = ['V006', 'V018', 'V032']
lugar = ['V007', 'V019', 'V033']

index_violencia = 2

filtered_df = novo_df[novo_df[violencias[index_violencia]] == 'Não']

# Extract person_keys
person_keys = filtered_df['person_key']

# Filter novo_df for rows with these person_keys and select columns
filtered_columns_df = dataset[dataset['person_key'].isin(person_keys)][[frequencia[index_violencia], relacionamento[index_violencia], lugar[index_violencia], 'Q11009']]

# Get value counts for each column
frequencia_counts = filtered_columns_df[frequencia[index_violencia]].value_counts(dropna=False)
relacionamento_counts = filtered_columns_df[relacionamento[index_violencia]].value_counts(dropna=False)
lugar_counts = filtered_columns_df[lugar[index_violencia]].value_counts(dropna=False)
toc_counts = filtered_columns_df['Q11009'].value_counts(dropna=False)

# Print the value counts for each column
print(violencias[index_violencia])
print('-------------------------------------')
print("Value counts for column 'frequencia':")
print(frequencia_counts)
print("\nValue counts for column 'relacionamento':")
print(relacionamento_counts)
print("\nValue counts for column 'lugar':")
print(lugar_counts)
print("\nValue counts for column 'toc':")
print(toc_counts)
print('-------------------------------------')

dataset_null = filtered_columns_df[[frequencia[index_violencia], relacionamento[index_violencia], lugar[index_violencia]]].isnull().all(axis=1)
toc = filtered_columns_df.loc[dataset_null, 'Q11009'].value_counts(dropna=False)

print("\nValue counts for column 'toc' when all is null:")
print(toc)

violencia_sexual
-------------------------------------
Value counts for column 'frequencia':
V029
NaN    4034
Name: count, dtype: int64

Value counts for column 'relacionamento':
V032
NaN    4034
Name: count, dtype: int64

Value counts for column 'lugar':
V033
NaN    4034
Name: count, dtype: int64

Value counts for column 'toc':
Q11009
2    3806
1     228
Name: count, dtype: int64
-------------------------------------

Value counts for column 'toc' when all is null:
Q11009
2    3806
1     228
Name: count, dtype: int64

**maioria as violencias sexuais do sample escolhido nao tem relacionamento, local nem frequencia -> manter variaveis?**

In [ ]:
# novo_df.drop(columns=['violencia_sexual'], inplace=True)

## trabalho

In [ ]:
trabalho_df = pd.DataFrame(novo_df[['person_key']].copy())

In [ ]:
trabalho = ['E001', 'E002', 'E003', 'E004', 'E02601']
remunerado = ['E001', 'E01601', 'E01801']
aposentadoria = ['F001011']
multiplos_trabalhos = ['E011']

In [ ]:
result_df = check_and_create_status('tem_trabalho', trabalho, [1.0], [2.0])
result_df_2 = check_and_create_status('tem_trabalho_2', ['E011'], [1.0, 2.0, 3.0], [9.0])
trabalho_df = pd.merge(trabalho_df, result_df[['person_key', 'tem_trabalho']], on='person_key', how='left')
trabalho_df = pd.merge(trabalho_df, result_df_2[['person_key', 'tem_trabalho_2']], on='person_key', how='left')

In [ ]:
result_df = check_and_create_status('remunerado', remunerado, [1.0], [2.0])
trabalho_df = pd.merge(trabalho_df, result_df[['person_key', 'remunerado']], on='person_key', how='left')

In [ ]:
result_df = check_and_create_status('aposentadoria', aposentadoria, [1.0], [2.0])
trabalho_df = pd.merge(trabalho_df, result_df[['person_key', 'aposentadoria']], on='person_key', how='left')

In [ ]:
result_df = check_and_create_status('multiplos_trabalhos', multiplos_trabalhos, [2.0, 3.0], [1.0])
trabalho_df = pd.merge(trabalho_df, result_df[['person_key', 'multiplos_trabalhos']], on='person_key', how='left')

In [ ]:
trabalho_df = pd.merge(trabalho_df, dataset[['person_key','E01602', 'E01802', 'F001021']].copy(), on='person_key')
trabalho_df.rename(columns={'E01602': 'rendimento_trabalho_1', 'E01802':'rendimento_trabalho_2', 'F001021': 'rendimento_aposentadoria'}, inplace=True)

In [ ]:
# Assuming trabalho_df is your DataFrame

trabalho_df.loc[(trabalho_df['tem_trabalho'] == 'Sim') | (trabalho_df['tem_trabalho_2'] == 'Sim'), 'trabalho'] = 'Sim'
trabalho_df.loc[(trabalho_df['tem_trabalho'] != 'Sim') & (trabalho_df['tem_trabalho_2'] != 'Sim'), 'trabalho'] = 'Não'
trabalho_df.loc[(trabalho_df['tem_trabalho'] == 'Não Aplicável') & (trabalho_df['tem_trabalho_2'] == 'Não Aplicável'), 'trabalho'] = 'Não Aplicável'

# Drop the 'trabalho' column
trabalho_df.drop(columns=['tem_trabalho', 'tem_trabalho_2'], inplace=True)

In [ ]:
trabalho_df.loc[(trabalho_df['trabalho'] == 'Sim') & (trabalho_df['multiplos_trabalhos'] == 'Não Aplicável'), 'multiplos_trabalhos'] = 'Não'

In [ ]:
# Fill NaN values in specific columns with 0
trabalho_df[['rendimento_trabalho_1', 'rendimento_trabalho_2', 'rendimento_aposentadoria']] = \
    trabalho_df[['rendimento_trabalho_1', 'rendimento_trabalho_2', 'rendimento_aposentadoria']].fillna(0)

# Create a new column 'rendimento_trabalho' by summing 'rendimento_trabalho_1' and 'rendimento_trabalho_2'
trabalho_df['rendimento_trabalho'] = trabalho_df['rendimento_trabalho_1'] + trabalho_df['rendimento_trabalho_2']

# Drop the columns 'rendimento_trabalho_1' and 'rendimento_trabalho_2'
trabalho_df.drop(columns=['rendimento_trabalho_1', 'rendimento_trabalho_2'], inplace=True)

In [ ]:
trabalho_df

,person_key,remunerado,aposentadoria,multiplos_trabalhos,rendimento_aposentadoria,trabalho,rendimento_trabalho
0,11_1110011_110003808_2_1,Sim,Não,Sim,0.0,Sim,2400.0
1,11_1110011_110003808_7_1,Não,Não,Não Aplicável,0.0,Não,0.0
2,11_1110011_110007557_7_1,Sim,Não,Sim,0.0,Sim,13700.0
3,11_1110011_110008644_4_2,Sim,Não,Não,0.0,Sim,2000.0
4,11_1110011_110008644_15_1,Não,Sim,Não Aplicável,998.0,Não,0.0
...,...,...,...,...,...,...,...
4787,53_5310211_530000135_7_1,Não,Não,Não Aplicável,0.0,Não,0.0
4788,53_5310211_530037460_2_1,Sim,Não,Não,0.0,Sim,6000.0
4789,53_5310211_530042333_3_1,Sim,Não,Não,0.0,Sim,1500.0
4790,53_5310212_530029819_15_1,Sim,Não,Não,0.0,Sim,200.0
4791,53_5310212_530033471_9_2,Sim,Não,Não,0.0,Sim,3000.0

### merge trabalho df com novo df

In [ ]:
novo_df = pd.merge(novo_df, trabalho_df, on='person_key', how='left')

In [ ]:
novo_df.loc[
    (
        (novo_df['trabalho'] == 'Não') & (novo_df['aposentadoria'] == 'Não') |
        (novo_df['trabalho'] == 'Sim') & (novo_df['remunerado'] == 'Não') |
        (novo_df['trabalho'] == 'Sim') & (novo_df['multiplos_trabalhos'] == 'Sim') |
        (
            (novo_df['trabalho'] == 'Sim') &
            (novo_df['multiplos_trabalhos'] == 'Não') &
            ((novo_df['rendimento_trabalho'] + novo_df['rendimento_aposentadoria']) < 1412)
        )
    ),
    'vulnerabilidade_trabalho'
] = 'Sim'

novo_df.loc[
    (
        (novo_df['trabalho'] == 'Não Aplicável') &
        (novo_df['aposentadoria'] == 'Não Aplicável') &
        (novo_df['remunerado'] == 'Não Aplicável') &
        (novo_df['multiplos_trabalhos'] == 'Não Aplicável')
    ),
    'vulnerabilidade_trabalho'
] = 'Não Aplicável'

# Fill NaN values in 'vulnerabilidade_trabalho' column with 'Não'
novo_df['vulnerabilidade_trabalho'].fillna('Não', inplace=True)

# Drop columns from novo_df that are present in trabalho_df except for 'person_key'
columns_to_drop = [col for col in trabalho_df.columns if col != 'person_key']
novo_df.drop(columns=columns_to_drop, inplace=True)

In [ ]:
novo_df

,person_key,sexo,idade,cor_raca,estado_civil,toc,violencia_psicologica,violencia_fisica,violencia_sexual,vulnerabilidade_trabalho
0,11_1110011_110003808_2_1,Mulher,Meia Idade,Preta,Solteiro(a),Não,Não,Não,Não,Sim
1,11_1110011_110003808_7_1,Mulher,Adulto,Branca,Casado(a),Não,Não,Não,Não,Sim
2,11_1110011_110007557_7_1,Mulher,Idade Madura,Branca,Solteiro(a),Não,Não,Não,Não,Sim
3,11_1110011_110008644_4_2,Homem,Jovem Adulto,Branca,Solteiro(a),Não,Não,Não,Não,Não
4,11_1110011_110008644_15_1,Mulher,Idade Madura,Parda,Divorciado(a) ou desquitado(a) ou separado(a) ...,Não,Não,Não,Não,Não
...,...,...,...,...,...,...,...,...,...,...
4787,53_5310211_530000135_7_1,Mulher,Adulto,Parda,Solteiro(a),Sim,Não,Não,Sim,Sim
4788,53_5310211_530037460_2_1,Mulher,Meia Idade,Parda,Casado(a),Sim,Não,Não,Não,Não
4789,53_5310211_530042333_3_1,Mulher,Meia Idade,Parda,Divorciado(a) ou desquitado(a) ou separado(a) ...,Sim,Não,Não,Não,Não
4790,53_5310212_530029819_15_1,Homem,Meia Idade,Preta,Solteiro(a),Sim,Sim,Não,Não,Sim
4791,53_5310212_530033471_9_2,Mulher,Meia Idade,Preta,Solteiro(a),Sim,Sim,Sim,Sim,Não

### teste

In [ ]:
trabalho_df[['trabalho', 'remunerado']].value_counts(dropna=False)

trabalho  remunerado
Sim       Sim           2599
Não       Não           1920
Sim       Não            273
Name: count, dtype: int64

In [ ]:
trabalho_df[['aposentadoria']].value_counts(dropna=False)

aposentadoria
Não              3735
Sim              1057
Name: count, dtype: int64

In [ ]:
trabalho_df[['remunerado']].value_counts(dropna=False)

remunerado
Sim           2599
Não           2193
Name: count, dtype: int64

In [ ]:
trabalho_df[['trabalho']].value_counts(dropna=False)

trabalho
Sim         2872
Não         1920
Name: count, dtype: int64

In [ ]:
trabalho_df[['multiplos_trabalhos']].value_counts(dropna=False)

multiplos_trabalhos
Não                    2636
Não Aplicável          1920
Sim                     236
Name: count, dtype: int64

In [ ]:
trabalho_df[['trabalho', 'multiplos_trabalhos']].value_counts(dropna=False)

trabalho  multiplos_trabalhos
Sim       Não                    2636
Não       Não Aplicável          1920
Sim       Sim                     236
Name: count, dtype: int64

In [ ]:
trabalho_df[(trabalho_df['trabalho'] == 'Sim') & (trabalho_df['remunerado'] == 'Não')][['aposentadoria', 'rendimento_trabalho', 'rendimento_aposentadoria']]

     aposentadoria  rendimento_trabalho  rendimento_aposentadoria
22             Não                  0.0                       0.0
25             Não                  0.0                       0.0
32             Não                  0.0                       0.0
51             Não                  0.0                       0.0
61             Sim                  0.0                     998.0
...            ...                  ...                       ...
4699           Não                  0.0                       0.0
4703           Não                  0.0                       0.0
4748           Não                  0.0                       0.0
4759           Não                  0.0                       0.0
4763           Não                  0.0                       0.0

[273 rows x 3 columns]

In [ ]:
trabalho_df[trabalho_df['person_key'] == '35_3553013_350047124_12_2']

,person_key,remunerado,aposentadoria,multiplos_trabalhos,rendimento_aposentadoria,trabalho,rendimento_trabalho
3126,35_3553013_350047124_12_2,Não,Não,Não Aplicável,0.0,Não,0.0

In [ ]:
novo_df[novo_df['person_key'] == '35_3553013_350047124_12_2']['vulnerabilidade_trabalho']

3126    Sim
Name: vulnerabilidade_trabalho, dtype: object

In [ ]:
novo_df[['vulnerabilidade_trabalho']].value_counts(dropna=False)

vulnerabilidade_trabalho
Sim                         2705
Não                         2087
Name: count, dtype: int64

In [ ]:
novo_df

,person_key,sexo,idade,cor_raca,estado_civil,toc,violencia_psicologica,violencia_fisica,violencia_sexual,vulnerabilidade_trabalho
0,11_1110011_110003808_2_1,Mulher,Meia Idade,Preta,Solteiro(a),Não,Não,Não,Não,Sim
1,11_1110011_110003808_7_1,Mulher,Adulto,Branca,Casado(a),Não,Não,Não,Não,Sim
2,11_1110011_110007557_7_1,Mulher,Idade Madura,Branca,Solteiro(a),Não,Não,Não,Não,Sim
3,11_1110011_110008644_4_2,Homem,Jovem Adulto,Branca,Solteiro(a),Não,Não,Não,Não,Não
4,11_1110011_110008644_15_1,Mulher,Idade Madura,Parda,Divorciado(a) ou desquitado(a) ou separado(a) ...,Não,Não,Não,Não,Não
...,...,...,...,...,...,...,...,...,...,...
4787,53_5310211_530000135_7_1,Mulher,Adulto,Parda,Solteiro(a),Sim,Não,Não,Sim,Sim
4788,53_5310211_530037460_2_1,Mulher,Meia Idade,Parda,Casado(a),Sim,Não,Não,Não,Não
4789,53_5310211_530042333_3_1,Mulher,Meia Idade,Parda,Divorciado(a) ou desquitado(a) ou separado(a) ...,Sim,Não,Não,Não,Não
4790,53_5310212_530029819_15_1,Homem,Meia Idade,Preta,Solteiro(a),Sim,Sim,Não,Não,Sim
4791,53_5310212_530033471_9_2,Mulher,Meia Idade,Preta,Solteiro(a),Sim,Sim,Sim,Sim,Não

## nivel de instrução

In [ ]:
dataset['VDD004A'].value_counts(dropna=False)

VDD004A
5    1298
2    1183
7    1154
6     349
3     331
4     256
1     221
Name: count, dtype: int64

In [ ]:
novo_df = pd.merge(novo_df, dataset[['person_key','VDD004A']], on='person_key', how='left')

In [ ]:
# Mapeamento dos valores para níveis de instrução
nivel_instrucao_mapping = {
    1: 'Sem instrução',
    2: 'Fundamental incompleto ou equivalente',
    3: 'Fundamental completo ou equivalente',
    4: 'Médio incompleto ou equivalente',
    5: 'Médio completo ou equivalente',
    6: 'Superior incompleto ou equivalente',
    7: 'Superior completo',
    None: 'Não Aplicável'
    # Adicione mais mapeamentos se necessário
}

# Definir os valores da coluna 'nivel_instrucao' com base no valor da coluna 'VDD004A'
novo_df['nivel_instrucao'] = novo_df['VDD004A'].map(nivel_instrucao_mapping)

In [ ]:
novo_df.drop(columns='VDD004A', inplace=True)

In [ ]:
novo_df['nivel_instrucao'].value_counts(dropna=False)

nivel_instrucao
Médio completo ou equivalente            1298
Fundamental incompleto ou equivalente    1183
Superior completo                        1154
Superior incompleto ou equivalente        349
Fundamental completo ou equivalente       331
Médio incompleto ou equivalente           256
Sem instrução                             221
Name: count, dtype: int64

## moradia

In [ ]:
moradia  = [
    'person_key',
    'A001',
    'A002010',
    'A003010',
    'A004010',
    'A01501',
    'A005010',
    'A00601',
    'A009010',
    'A01401',
    'V0022',
    'A011',
    'A016010',
    'A018013',
    'A018019',
    'A018017',
    'A01901'
]

In [ ]:
novo_df = pd.merge(novo_df, dataset[moradia], on='person_key', how='left')

In [ ]:
novo_df

,person_key,sexo,idade,cor_raca,estado_civil,toc,violencia_psicologica,violencia_fisica,violencia_sexual,vulnerabilidade_trabalho,...,A00601,A009010,A01401,V0022,A011,A016010,A018013,A018019,A018017,A01901
0,11_1110011_110003808_2_1,Mulher,Meia Idade,Preta,Solteiro(a),Não,Não,Não,Não,Sim,...,1,5,1,1,1,1,1,1,2,1
1,11_1110011_110003808_7_1,Mulher,Adulto,Branca,Casado(a),Não,Não,Não,Não,Sim,...,1,5,1,3,1,1,1,1,2,1
2,11_1110011_110007557_7_1,Mulher,Idade Madura,Branca,Solteiro(a),Não,Não,Não,Não,Sim,...,1,5,2,1,1,1,1,1,1,1
3,11_1110011_110008644_4_2,Homem,Jovem Adulto,Branca,Solteiro(a),Não,Não,Não,Não,Não,...,1,5,2,2,2,1,1,1,2,1
4,11_1110011_110008644_15_1,Mulher,Idade Madura,Parda,Divorciado(a) ou desquitado(a) ou separado(a) ...,Não,Não,Não,Não,Não,...,1,5,1,2,1,1,1,1,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4787,53_5310211_530000135_7_1,Mulher,Adulto,Parda,Solteiro(a),Sim,Não,Não,Sim,Sim,...,1,1,1,3,2,1,1,1,1,1
4788,53_5310211_530037460_2_1,Mulher,Meia Idade,Parda,Casado(a),Sim,Não,Não,Não,Não,...,1,1,1,3,2,1,1,1,2,1
4789,53_5310211_530042333_3_1,Mulher,Meia Idade,Parda,Divorciado(a) ou desquitado(a) ou separado(a) ...,Sim,Não,Não,Não,Não,...,1,1,1,1,1,1,1,1,2,1
4790,53_5310212_530029819_15_1,Homem,Meia Idade,Preta,Solteiro(a),Sim,Sim,Não,Não,Sim,...,1,1,1,1,1,1,1,1,2,2
4791,53_5310212_530033471_9_2,Mulher,Meia Idade,Preta,Solteiro(a),Sim,Sim,Sim,Sim,Não,...,1,1,2,4,3,1,1,1,2,1

In [ ]:
novo_df['A004010'].value_counts()

A004010
1    3772
3     596
2     397
5      15
4      12
Name: count, dtype: int64

In [ ]:
novo_df.loc[
    (
        (novo_df['A001'] == 3) | (novo_df['A002010'] == 2) | (novo_df['A002010'] == 3) | (novo_df['A004010'] == 4)
    ),
    'casas inadequadas'
] = 'Sim'


novo_df.loc[
    (
        # sem saneamento básico
        (
            (novo_df['A01501'] == 3) | (novo_df['A01501'] == 4) | (novo_df['A01501'] == 5) | (novo_df['A01501'] == 6)
        )
      ),
    'sem saneamento básico'
] = 'Sim'

novo_df.loc[
    (
        # origem da água inadequada
        (
            (novo_df['A005010'] == 3) | (novo_df['A005010'] == 5)
        )
      ),
    'origem da água inadequada'
] = 'Sim'

novo_df.loc[
    (
        # depósito da água inadequado
        (
            (novo_df['A00601'] == 3) |
            ((novo_df['A009010'] == 2) | (novo_df['A009010'] == 6))
        )
      ),
    'depósito da água inadequado'
] = 'Sim'

novo_df.loc[
    (
        # instalação sanitária inadequada
        (
            (novo_df['A01401'] == 0) |
            ((novo_df['V0022'] / novo_df['A01401']) > 3)
        )
      ),
    'instalação sanitária inadequada'
] = 'Sim'

novo_df.loc[
    (
        # destino do lixo inadequado
        (
            (novo_df['A016010'] == 3) | (novo_df['A016010'] == 4) | (novo_df['A016010'] == 5)
        )
      ),
    'destino do lixo inadequado'
] = 'Sim'


novo_df.loc[
    (
        # mais de 3 pessoas por dormitório
        (
            ((novo_df['V0022'] / novo_df['A011']) > 3)
        )
      ),
    'mais de 3 pessoas por dormitório'
] = 'Sim'

novo_df.loc[
    (
        # falta de eletrodomésticos básicos
        (
            (novo_df['A018013'] == 2) |
            ((novo_df['A018019'] == 2) & (novo_df['A018017'] == 2)) |
            (novo_df['A01901'] == 2)
        )
    ),
    'falta de eletrodomésticos básicos'
] = 'Sim'

In [ ]:
# List of columns indicating various conditions
condition_columns = [
    'casas inadequadas',
    'sem saneamento básico',
    'origem da água inadequada',
    'depósito da água inadequado',
    'instalação sanitária inadequada',
    'destino do lixo inadequado',
    'mais de 3 pessoas por dormitório',
    'falta de eletrodomésticos básicos'
]

# Check if any of the conditions are True for each row
novo_df['moradia'] = novo_df[condition_columns].eq('Sim').any(axis=1).replace({True: 'Habitação Não Saudável', False: 'Habitação Saudável'})

In [ ]:
nao_aplicavel_df = pd.DataFrame()
nao_aplicavel_df['moradia'] = novo_df[moradia[1:]].isnull().all(axis=1)

In [ ]:
nao_aplicavel_list = nao_aplicavel_df[nao_aplicavel_df['moradia'] == True].index.tolist()

In [ ]:
for index in nao_aplicavel_list:
  novo_df.loc[index, 'moradia'] = 'Não Aplicável'

In [ ]:
# Drop columns from novo_df that are present in trabalho_df except for 'person_key'
columns_to_drop = [col for col in moradia if col != 'person_key']
novo_df.drop(columns=columns_to_drop, inplace=True)

columns_to_drop = [col for col in condition_columns if col != 'person_key']
novo_df.drop(columns=columns_to_drop, inplace=True)

In [ ]:
novo_df['moradia'].value_counts()

moradia
Habitação Não Saudável    2911
Habitação Saudável        1881
Name: count, dtype: int64

## Utilização dos serviços de saúde

In [ ]:
novo_df = pd.merge(novo_df, dataset[['person_key', 'J01101', 'J012']], on='person_key', how='left')

In [ ]:
novo_df['J012'].value_counts(dropna=False)

J012
2.0      734
3.0      677
1.0      626
4.0      552
6.0      402
10.0     384
5.0      359
NaN      289
12.0     215
8.0      185
7.0       74
20.0      64
15.0      64
9.0       34
24.0      26
30.0      19
11.0      16
40.0       8
18.0       8
48.0       8
14.0       6
36.0       5
25.0       5
16.0       5
13.0       5
50.0       3
100.0      2
52.0       2
180.0      2
60.0       2
33.0       1
21.0       1
108.0      1
58.0       1
200.0      1
96.0       1
45.0       1
32.0       1
17.0       1
28.0       1
35.0       1
Name: count, dtype: int64

In [ ]:
novo_df[['J01101', 'J012']].value_counts(dropna=False)

J01101  J012
1       2.0      734
        3.0      677
        1.0      626
        4.0      552
        6.0      402
        10.0     384
        5.0      359
        12.0     215
2       NaN      199
1       8.0      185
        7.0       74
        15.0      64
        20.0      64
4       NaN       50
3       NaN       36
1       9.0       34
        24.0      26
        30.0      19
        11.0      16
        48.0       8
        40.0       8
        18.0       8
        14.0       6
        25.0       5
        16.0       5
        36.0       5
        13.0       5
5       NaN        4
1       50.0       3
        52.0       2
        60.0       2
        100.0      2
        180.0      2
        35.0       1
        45.0       1
        33.0       1
        58.0       1
        96.0       1
        108.0      1
        200.0      1
        32.0       1
        21.0       1
        17.0       1
        28.0       1
Name: count, dtype: int64

In [ ]:
novo_df['J012'].describe(percentiles=[0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 0.99, 1])

count    4503.000000
mean        5.743504
std         7.854473
min         1.000000
20%         2.000000
30%         2.000000
40%         3.000000
50%         4.000000
60%         5.000000
70%         6.000000
80%         8.000000
90%        12.000000
95%        15.000000
99%        30.000000
100%      200.000000
max       200.000000
Name: J012, dtype: float64

In [ ]:
novo_df.loc[
      (
        (novo_df['J01101'] == 9) & (novo_df['J012'] == 999)
      ),
    'utilizacao_servicos_saude'
] = 'Ignorado'

novo_df.loc[
      (
        novo_df['J01101'].isnull()
      ),
    'utilizacao_servicos_saude'
] = 'Não Aplicável'

novo_df.loc[
      (
        (novo_df['J01101'] == 2) | (novo_df['J01101'] == 3) | (novo_df['J01101'] == 4) | (novo_df['J01101'] == 5)
      ),
    'utilizacao_servicos_saude'
] = '< 1x por ano'

novo_df.loc[
      (
        (novo_df['J01101'] == 1)
      ),
    'utilizacao_servicos_saude'
] = '1-5x por ano'

novo_df.loc[
      (
       (novo_df['J01101'] == 1) & ( novo_df['J012'] >= 6) & (novo_df['J012'] <= 10)
      ),
    'utilizacao_servicos_saude'
] = '6-10x por ano'

novo_df.loc[
      (
        (novo_df['J01101'] == 1) & (novo_df['J012'] >= 11) & (novo_df['J012'] <= 15)
      ),
    'utilizacao_servicos_saude'
] = '11-15x por ano'

novo_df.loc[
      (
        (novo_df['J01101'] == 1) & (novo_df['J012'] > 15)
      ),
    'utilizacao_servicos_saude'
] = '> 15x por ano'

In [ ]:
novo_df.drop(columns=['J012', 'J01101'], inplace=True)

In [ ]:
novo_df['utilizacao_servicos_saude'].value_counts(dropna=False)

utilizacao_servicos_saude
1-5x por ano      2948
6-10x por ano     1079
11-15x por ano     306
< 1x por ano       289
> 15x por ano      170
Name: count, dtype: int64

## Plano de Saúde

In [ ]:
novo_df = pd.merge(novo_df, dataset[['person_key', 'I00102',  'I001021']], on='person_key', how='left')

In [ ]:
novo_df[['I00102', 'I001021']].value_counts(dropna=False)

I00102  I001021
2       NaN        3131
1       1.0        1607
        2.0          53
        3.0           1
Name: count, dtype: int64

In [ ]:
novo_df.loc[
      (
        novo_df['I00102'] == 9
      ),
    'plano_saude'
] = 'Ignorado'

novo_df.loc[
      (
        novo_df['I00102'].isnull()
      ),
    'plano_saude'
] = 'Não Aplicável'

novo_df.loc[
      (
        novo_df['I00102'] == 2
      ),
    'plano_saude'
] = '0'

novo_df.loc[
      (
       ( novo_df['I001021'] == 1) | (novo_df['I001021'] == 2) | (novo_df['I001021'] > 2)
      ),
    'plano_saude'
] = '1 ou mais'

In [ ]:
novo_df.drop(columns=['I00102', 'I001021'], inplace=True)

In [ ]:
novo_df['plano_saude'].value_counts(dropna=False)

plano_saude
0            3131
1 ou mais    1661
Name: count, dtype: int64

## doenças cronicas pre existentes

In [ ]:
doencas_cronicas_df = pd.DataFrame(novo_df[['person_key']].copy())

In [ ]:
doencas_cronicas = ['Q00201', 'Q03001', 'Q060', 'Q06306', 'Q068', 'Q074', 'Q079', 'Q088', 'Q11604', 'Q120', 'Q124']

In [ ]:
result_df = check_and_create_status('doencas_cronicas', doencas_cronicas, [1.0], [2.0])
doencas_cronicas_df = pd.merge(doencas_cronicas_df, result_df[['person_key', 'doencas_cronicas']], on='person_key', how='left')
novo_df = pd.merge(novo_df, doencas_cronicas_df, on='person_key', how='left')

In [ ]:
novo_df['doencas_cronicas'].value_counts(dropna=False)

doencas_cronicas
Sim    2866
Não    1926
Name: count, dtype: int64

In [ ]:
novo_df

,person_key,sexo,idade,cor_raca,estado_civil,toc,violencia_psicologica,violencia_fisica,violencia_sexual,vulnerabilidade_trabalho,nivel_instrucao,moradia,utilizacao_servicos_saude,plano_saude,doencas_cronicas
0,11_1110011_110003808_2_1,Mulher,Meia Idade,Preta,Solteiro(a),Não,Não,Não,Não,Sim,Médio completo ou equivalente,Habitação Não Saudável,1-5x por ano,0,Sim
1,11_1110011_110003808_7_1,Mulher,Adulto,Branca,Casado(a),Não,Não,Não,Não,Sim,Superior incompleto ou equivalente,Habitação Não Saudável,6-10x por ano,0,Sim
2,11_1110011_110007557_7_1,Mulher,Idade Madura,Branca,Solteiro(a),Não,Não,Não,Não,Sim,Superior completo,Habitação Não Saudável,6-10x por ano,1 ou mais,Sim
3,11_1110011_110008644_4_2,Homem,Jovem Adulto,Branca,Solteiro(a),Não,Não,Não,Não,Não,Médio completo ou equivalente,Habitação Não Saudável,1-5x por ano,0,Não
4,11_1110011_110008644_15_1,Mulher,Idade Madura,Parda,Divorciado(a) ou desquitado(a) ou separado(a) ...,Não,Não,Não,Não,Não,Fundamental incompleto ou equivalente,Habitação Não Saudável,6-10x por ano,0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4787,53_5310211_530000135_7_1,Mulher,Adulto,Parda,Solteiro(a),Sim,Não,Não,Sim,Sim,Médio completo ou equivalente,Habitação Saudável,6-10x por ano,0,Não
4788,53_5310211_530037460_2_1,Mulher,Meia Idade,Parda,Casado(a),Sim,Não,Não,Não,Não,Médio completo ou equivalente,Habitação Saudável,6-10x por ano,1 ou mais,Sim
4789,53_5310211_530042333_3_1,Mulher,Meia Idade,Parda,Divorciado(a) ou desquitado(a) ou separado(a) ...,Sim,Não,Não,Não,Não,Médio incompleto ou equivalente,Habitação Saudável,6-10x por ano,0,Sim
4790,53_5310212_530029819_15_1,Homem,Meia Idade,Preta,Solteiro(a),Sim,Sim,Não,Não,Sim,Fundamental incompleto ou equivalente,Habitação Não Saudável,1-5x por ano,0,Sim
4791,53_5310212_530033471_9_2,Mulher,Meia Idade,Preta,Solteiro(a),Sim,Sim,Sim,Sim,Não,Superior completo,Habitação Saudável,1-5x por ano,0,Sim

In [ ]:
dataset.loc[dataset['person_key'] == '32_3220012_320055600_13_2', doencas_cronicas]

      Q00201  Q03001  Q060  Q06306  Q068  Q074  Q079  Q088  Q11604  Q120  Q124
2384     1.0     2.0   2.0       2     2     2     2     2       2     2     2

In [ ]:
dataset.loc[dataset['person_key'] == '41_4120011_410151694_1_3', doencas_cronicas]

      Q00201  Q03001  Q060  Q06306  Q068  Q074  Q079  Q088  Q11604  Q120  Q124
3287     2.0     2.0   2.0       2     2     2     2     2       2     2     2

## sofrimentos mentais pre existentes

In [ ]:
sofrimentos_mentais_df = pd.DataFrame(novo_df[['person_key']].copy())

In [ ]:
sofrimentos_mentais  = ['Q092', 'Q11007', 'Q11008', 'Q11010']

In [ ]:
result_df = check_and_create_status('sofrimentos_mentais', sofrimentos_mentais, [1.0], [2.0])
sofrimentos_mentais_df = pd.merge(sofrimentos_mentais_df, result_df[['person_key', 'sofrimentos_mentais']], on='person_key', how='left')
novo_df = pd.merge(novo_df, sofrimentos_mentais_df, on='person_key', how='left')

In [ ]:
novo_df['sofrimentos_mentais'].value_counts(dropna=False)

sofrimentos_mentais
Sim    4464
Não     328
Name: count, dtype: int64

In [ ]:
novo_df

,person_key,sexo,idade,cor_raca,estado_civil,toc,violencia_psicologica,violencia_fisica,violencia_sexual,vulnerabilidade_trabalho,nivel_instrucao,moradia,utilizacao_servicos_saude,plano_saude,doencas_cronicas,sofrimentos_mentais
0,11_1110011_110003808_2_1,Mulher,Meia Idade,Preta,Solteiro(a),Não,Não,Não,Não,Sim,Médio completo ou equivalente,Habitação Não Saudável,1-5x por ano,0,Sim,Sim
1,11_1110011_110003808_7_1,Mulher,Adulto,Branca,Casado(a),Não,Não,Não,Não,Sim,Superior incompleto ou equivalente,Habitação Não Saudável,6-10x por ano,0,Sim,Sim
2,11_1110011_110007557_7_1,Mulher,Idade Madura,Branca,Solteiro(a),Não,Não,Não,Não,Sim,Superior completo,Habitação Não Saudável,6-10x por ano,1 ou mais,Sim,Sim
3,11_1110011_110008644_4_2,Homem,Jovem Adulto,Branca,Solteiro(a),Não,Não,Não,Não,Não,Médio completo ou equivalente,Habitação Não Saudável,1-5x por ano,0,Não,Sim
4,11_1110011_110008644_15_1,Mulher,Idade Madura,Parda,Divorciado(a) ou desquitado(a) ou separado(a) ...,Não,Não,Não,Não,Não,Fundamental incompleto ou equivalente,Habitação Não Saudável,6-10x por ano,0,Sim,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4787,53_5310211_530000135_7_1,Mulher,Adulto,Parda,Solteiro(a),Sim,Não,Não,Sim,Sim,Médio completo ou equivalente,Habitação Saudável,6-10x por ano,0,Não,Não
4788,53_5310211_530037460_2_1,Mulher,Meia Idade,Parda,Casado(a),Sim,Não,Não,Não,Não,Médio completo ou equivalente,Habitação Saudável,6-10x por ano,1 ou mais,Sim,Sim
4789,53_5310211_530042333_3_1,Mulher,Meia Idade,Parda,Divorciado(a) ou desquitado(a) ou separado(a) ...,Sim,Não,Não,Não,Não,Médio incompleto ou equivalente,Habitação Saudável,6-10x por ano,0,Sim,Sim
4790,53_5310212_530029819_15_1,Homem,Meia Idade,Preta,Solteiro(a),Sim,Sim,Não,Não,Sim,Fundamental incompleto ou equivalente,Habitação Não Saudável,1-5x por ano,0,Sim,Sim
4791,53_5310212_530033471_9_2,Mulher,Meia Idade,Preta,Solteiro(a),Sim,Sim,Sim,Sim,Não,Superior completo,Habitação Saudável,1-5x por ano,0,Sim,Sim

In [ ]:
dataset.loc[dataset['person_key'] == '53_5310211_530000135_7_1', sofrimentos_mentais]

      Q092  Q11007  Q11008  Q11010
4787     2       2       2       2

In [ ]:
dataset.loc[dataset['person_key'] == '53_5310211_530037460_2_1', sofrimentos_mentais]

      Q092  Q11007  Q11008  Q11010
4788     1       2       2       1

In [ ]:
dataset['Q092'].value_counts(dropna=False)

Q092
2    2549
1    2243
Name: count, dtype: int64

In [ ]:
dataset['Q11007'].value_counts(dropna=False)

Q11007
2    4495
1     297
Name: count, dtype: int64

In [ ]:
dataset['Q11008'].value_counts(dropna=False)

Q11008
2    4313
1     479
Name: count, dtype: int64

In [ ]:
dataset['Q11010'].value_counts(dropna=False)

Q11010
1    3653
2    1139
Name: count, dtype: int64

# Variaveis Comportamentais

## Ingestão de Alcool

In [ ]:
novo_df = pd.merge(novo_df, dataset[['person_key', 'P027',  'P02801']], on='person_key', how='left')

In [ ]:
novo_df[['P027',  'P02801']].value_counts(dropna=False)

P027  P02801
1     NaN       2955
2     NaN        582
3     1.0        494
      2.0        297
      0.0        212
      3.0        130
      7.0         51
      4.0         36
      5.0         24
      6.0         11
Name: count, dtype: int64

In [ ]:
novo_df.loc[
      (
        (novo_df['P027'] == 9) & (novo_df['P02801'] == 9)
      ),
    'ingestao_alcool'
] = 'Ignorado'

novo_df.loc[
      (
        novo_df['P027'].isnull()
      ),
    'ingestao_alcool'
] = 'Não Aplicável'

novo_df.loc[
      (
        novo_df['P027'] == 1
      ),
    'ingestao_alcool'
] = 'Nunca'

novo_df.loc[
      (
        ((novo_df['P027'] == 2) | (novo_df['P027'] == 3)) & (novo_df['P02801'] == 0)
      ),
    'ingestao_alcool'
] = '< 1x por semana'

novo_df.loc[
      (
        (novo_df['P027'] == 2) & (novo_df['P02801'].isnull())
      ),
    'ingestao_alcool'
] = '< 1x por semana'

novo_df.loc[
      (
        ((novo_df['P027'] == 2) | (novo_df['P027'] == 3)) & ((novo_df['P02801'] >= 1) & (novo_df['P02801'] <= 3))
      ),
    'ingestao_alcool'
] = '1-3x por semana'

novo_df.loc[
      (
        ((novo_df['P027'] == 2) | (novo_df['P027'] == 3)) & ((novo_df['P02801'] >= 4) & (novo_df['P02801'] <= 6))
      ),
    'ingestao_alcool'
] = '4-6x por semana'

novo_df.loc[
      (
        ((novo_df['P027'] == 2) | (novo_df['P027'] == 3)) & (novo_df['P02801'] >= 7)
      ),
    'ingestao_alcool'
] = 'Todo dia'

In [ ]:
novo_df[['P027', 'P02801', 'ingestao_alcool']].value_counts(dropna=False)

P027  P02801  ingestao_alcool
1     NaN     Nunca              2955
2     NaN     < 1x por semana     582
3     1.0     1-3x por semana     494
      2.0     1-3x por semana     297
      0.0     < 1x por semana     212
      3.0     1-3x por semana     130
      7.0     Todo dia             51
      4.0     4-6x por semana      36
      5.0     4-6x por semana      24
      6.0     4-6x por semana      11
Name: count, dtype: int64

In [ ]:
novo_df.drop(columns=['P027', 'P02801'], inplace=True)

In [ ]:
novo_df['ingestao_alcool'].value_counts(dropna=False)

ingestao_alcool
Nunca              2955
1-3x por semana     921
< 1x por semana     794
4-6x por semana      71
Todo dia             51
Name: count, dtype: int64

## Tabaco

In [ ]:
novo_df = pd.merge(novo_df, dataset[['person_key', 'P050', 'P052', 'P053']], on='person_key', how='left')

In [ ]:
teste = dataset.copy()
teste['tempo_fumando'] = teste['C008'] - teste['P053']

In [ ]:
teste[['C008', 'P053', 'tempo_fumando']][teste['tempo_fumando'] > 70]

      C008  P053  tempo_fumando
744     91  15.0           76.0
785     95  20.0           75.0
1930    86   7.0           79.0
2128    90  14.0           76.0
2968    94  15.0           79.0
3027    92  16.0           76.0
3124    83   8.0           75.0
3149    87  14.0           73.0
3298    93  18.0           75.0
4360    85   7.0           78.0

In [ ]:
teste['tempo_fumando'].describe(percentiles=[0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 0.99, 1])

count    1874.000000
mean       30.318036
std        16.216113
min         0.000000
20%        15.000000
30%        20.000000
40%        25.000000
50%        30.000000
60%        35.000000
70%        40.000000
80%        45.000000
90%        51.000000
95%        57.350000
99%        68.000000
100%       79.000000
max        79.000000
Name: tempo_fumando, dtype: float64

In [ ]:
novo_df.loc[
    (
        (novo_df[['P050', 'P052', 'P053']] == 9).all(axis=1)
    ),
    'tabaco'
] = 'Ignorado'

novo_df.loc[
    (
        novo_df[['P050', 'P052', 'P053']].isnull().all(axis=1)
    ),
    'tabaco'
] = 'Não Aplicável'

novo_df.loc[
      (
        (novo_df['P052'] == 3)
      ),
    'tabaco'
] = 'Nunca Fumou'

novo_df.loc[
      (
        (novo_df['P050'] == 3) & ((novo_df['P052'] == 1) | (novo_df['P052'] == 2))
      ),
    'tabaco'
] = 'Já foi fumante, mas não fuma atualmente'

novo_df.loc[
      (
        (novo_df['P050'] == 2)
      ),
    'tabaco'
] = 'Fuma ocasionalmente'

novo_df.loc[
      (
        (novo_df['P050'] == 1)
      ),
    'tabaco'
] = 'Fuma diariamente'

# novo_df.loc[
#       (
#         (novo_df['P050'] == 1) & (novo_df['idade'] -  novo_df['P053'] < 15)
#       ),
#     'tabaco'
# ] = 'Fuma diariamente há menos de 15 anos'

# novo_df.loc[
#       (
#         (novo_df['P050'] == 1) & ((novo_df['idade'] -  novo_df['P053'] >= 15) & (novo_df['idade'] -  novo_df['P053'] < 30))
#       ),
#     'tabaco'
# ] = 'Fuma diariamente entre 15 e 30 anos'

# novo_df.loc[
#       (
#         (novo_df['P050'] == 1) & ((novo_df['idade'] -  novo_df['P053'] >= 30) & (novo_df['idade'] -  novo_df['P053'] < 50))
#       ),
#     'tabaco'
# ] = 'Fuma diariamente entre 30 e 50 anos'

# novo_df.loc[
#       (
#         (novo_df['P050'] == 1) & ((novo_df['idade'] -  novo_df['P053'] >= 50) & (novo_df['idade'] -  novo_df['P053'] < 70))
#       ),
#     'tabaco'
# ] = 'Fuma diariamente entre 50 e 70 anos'

# novo_df.loc[
#       (
#         (novo_df['P050'] == 1) & (novo_df['idade'] -  novo_df['P053'] >= 70)
#       ),
#     'tabaco'
# ] = 'Fuma diariamente há mais de 70 anos'

In [ ]:
novo_df[['P050', 'P052', 'P053', 'tabaco']].value_counts(dropna=False)

P050  P052  P053  tabaco
3     3.0   NaN   Nunca Fumou                                2696
      1.0   15.0  Já foi fumante, mas não fuma atualmente     191
      2.0   NaN   Já foi fumante, mas não fuma atualmente     184
      1.0   18.0  Já foi fumante, mas não fuma atualmente     133
            14.0  Já foi fumante, mas não fuma atualmente     109
                                                             ...
2     NaN   22.0  Fuma ocasionalmente                           1
            27.0  Fuma ocasionalmente                           1
            28.0  Fuma ocasionalmente                           1
            30.0  Fuma ocasionalmente                           1
1     NaN   6.0   Fuma diariamente                              1
Name: count, Length: 97, dtype: int64

In [ ]:
novo_df.drop(columns=[ 'P050', 'P052', 'P053'], inplace=True)

In [ ]:
novo_df['tabaco'].value_counts(dropna=False)

tabaco
Nunca Fumou                                2696
Já foi fumante, mas não fuma atualmente    1403
Fuma diariamente                            608
Fuma ocasionalmente                          85
Name: count, dtype: int64

## Frequência escovação

In [ ]:
novo_df = pd.merge(novo_df, dataset[['person_key', 'U00101', 'U00204']], on='person_key', how='left')

In [ ]:
novo_df[['U00101', 'U00204']].value_counts(dropna=False)

U00101  U00204
1.0     1         3044
2.0     1         1437
3.0     1          233
NaN     2           55
4.0     1           23
Name: count, dtype: int64

In [ ]:
novo_df.loc[
      (
        (novo_df['U00101'] == 9) & (novo_df['U00204'] == 9)
      ),
    'frequencia_escovacao_dentaria'
] = 'Ignorado'

novo_df.loc[
      (
        novo_df['U00101'].isnull() & novo_df['U00204'].isnull()
      ),
    'frequencia_escovacao_dentaria'
] = 'Não Aplicável'

novo_df.loc[
      (
        (novo_df['U00204'] == 1) & (novo_df['U00101'] == 1)
      ),
    'frequencia_escovacao_dentaria'
] = '3x ou mais por dia'

novo_df.loc[
      (
        (novo_df['U00204'] == 1) & (novo_df['U00101'] == 2)
      ),
    'frequencia_escovacao_dentaria'
] = '2x por dia'

novo_df.loc[
      (
        (novo_df['U00204'] == 1) & (novo_df['U00101'] == 3)
      ),
    'frequencia_escovacao_dentaria'
] = '1x por dia'

novo_df.loc[
      (
        ((novo_df['U00204'] == 1) & (novo_df['U00101'] == 4)) | (novo_df['U00204'] == 2)
      ),
    'frequencia_escovacao_dentaria'
] = '< 1x por dia'

In [ ]:
novo_df.drop(columns=['U00101', 'U00204'], inplace=True)

In [ ]:
novo_df['frequencia_escovacao_dentaria'].value_counts(dropna=False)

frequencia_escovacao_dentaria
3x ou mais por dia    3044
2x por dia            1437
1x por dia             233
< 1x por dia            78
Name: count, dtype: int64

## Exercicio Fisico

In [ ]:
dataset[['P034', 'P035', 'P03701', 'P03702']]

      P034  P035  P03701  P03702
0        2   NaN     NaN     NaN
1        2   NaN     NaN     NaN
2        2   NaN     NaN     NaN
3        2   NaN     NaN     NaN
4        2   NaN     NaN     NaN
...    ...   ...     ...     ...
4787     1   3.0     1.0     0.0
4788     2   NaN     NaN     NaN
4789     2   NaN     NaN     NaN
4790     1   3.0     0.0    30.0
4791     1   2.0     1.0     0.0

[4792 rows x 4 columns]

In [ ]:
dataset.loc[dataset['P035'].notnull() , ['P034', 'P035', 'P03701', 'P03702']]

      P034  P035  P03701  P03702
5        1   3.0     1.0    15.0
11       1   6.0     0.0    30.0
12       1   7.0     1.0    30.0
25       1   5.0     0.0    55.0
28       1   4.0     0.0    30.0
...    ...   ...     ...     ...
4783     1   6.0     1.0    30.0
4786     1   4.0     1.0     0.0
4787     1   3.0     1.0     0.0
4790     1   3.0     0.0    30.0
4791     1   2.0     1.0     0.0

[2153 rows x 4 columns]

In [ ]:
dataset.loc[dataset['P035'].notnull() & (dataset['P03701'] != 0) & (dataset['P03702'] != 0) & (dataset['P035'] == 0) , ['P034', 'P035', 'P03701', 'P03702']]

      P034  P035  P03701  P03702
34       1   0.0     NaN     NaN
60       1   0.0     NaN     NaN
136      1   0.0     NaN     NaN
191      1   0.0     NaN     NaN
219      1   0.0     NaN     NaN
...    ...   ...     ...     ...
4441     1   0.0     NaN     NaN
4452     1   0.0     NaN     NaN
4489     1   0.0     NaN     NaN
4520     1   0.0     NaN     NaN
4558     1   0.0     NaN     NaN

[94 rows x 4 columns]

In [ ]:
dataset[['P03702']].value_counts()

P03702
0.0       1129
30.0       502
40.0       171
45.0        63
20.0        59
50.0        56
15.0        38
10.0        24
25.0         6
35.0         6
59.0         2
5.0          1
16.0         1
55.0         1
Name: count, dtype: int64

In [ ]:
teste = dataset.copy()
teste['tempo_ex_fisico'] = ((teste['P035']) * (teste['P03701'] + (teste['P03702'] / 60)))

In [ ]:
teste[teste['P035'].notnull()][['tempo_ex_fisico', 'P035', 'P03701', 'P03702']]

      tempo_ex_fisico  P035  P03701  P03702
5            3.750000   3.0     1.0    15.0
11           3.000000   6.0     0.0    30.0
12          10.500000   7.0     1.0    30.0
25           4.583333   5.0     0.0    55.0
28           2.000000   4.0     0.0    30.0
...               ...   ...     ...     ...
4783         9.000000   6.0     1.0    30.0
4786         4.000000   4.0     1.0     0.0
4787         3.000000   3.0     1.0     0.0
4790         1.500000   3.0     0.0    30.0
4791         2.000000   2.0     1.0     0.0

[2153 rows x 4 columns]

In [ ]:
novo_df = pd.merge(novo_df, dataset[['person_key', 'P034', 'P035', 'P03701', 'P03702']], on='person_key', how='left')

In [ ]:
novo_df['tempo_ex_fisico'] = ((teste['P035']) * (teste['P03701'] + (teste['P03702'] / 60)))

In [ ]:
novo_df['tempo_ex_fisico'].describe(percentiles=[0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 0.99, 1])

count    2059.000000
mean        4.207131
std         3.300877
min         0.166667
20%         2.000000
30%         2.000000
40%         3.000000
50%         3.000000
60%         4.000000
70%         5.000000
80%         6.000000
90%         7.500000
95%        10.000000
99%        15.000000
100%       53.750000
max        53.750000
Name: tempo_ex_fisico, dtype: float64

In [ ]:
novo_df.loc[
    (
        (novo_df[['P034', 'P035', 'P03701', 'P03702']] == 9).all(axis=1)
    ),
    'exercicio_fisico'
] = 'Ignorado'

novo_df.loc[
    (
        novo_df[['P034', 'P035', 'P03701', 'P03702']].isnull().all(axis=1)
    ),
    'exercicio_fisico'
] = 'Não Aplicável'

novo_df.loc[
      (
        (novo_df['P034'] == 2) | (novo_df['P035'] == 0)
      ),
    'exercicio_fisico'
] = 'Não Pratica Regularmente'

novo_df.loc[
      (
        (novo_df['P034'] == 1) & (novo_df['tempo_ex_fisico'] < 2)
      ),
    'exercicio_fisico'
] = '< 2h por semana'

novo_df.loc[
    (
        (novo_df['P034'] == 1) &
        (novo_df['tempo_ex_fisico'] >= 2) &
        (novo_df['tempo_ex_fisico'] < 4)
    ),
    'exercicio_fisico'
] = '2 - 4h por semana'


novo_df.loc[
      (
        (novo_df['P034'] == 1) &
        (novo_df['tempo_ex_fisico'] >= 4) &
        (novo_df['tempo_ex_fisico'] < 6)
      ),
    'exercicio_fisico'
] = '4 - 6h por semana'

novo_df.loc[
      (
        (novo_df['P034'] == 1) &
        (novo_df['tempo_ex_fisico'] >= 6)
      ),
    'exercicio_fisico'
] = '>= 6h por semana'

In [ ]:
novo_df.drop(columns=['tempo_ex_fisico', 'P034', 'P035', 'P03701', 'P03702'], inplace=True)

In [ ]:
# novo_df[['exercicio_fisico', 'P034', 'P035', 'P03701', 'P03702']].value_counts(dropna=False)

In [ ]:
# novo_df.loc[novo_df['tempo_ex_fisico'].notnull() , ['exercicio_fisico', 'tempo_ex_fisico', 'P034', 'P035', 'P03701', 'P03702']]

In [ ]:
novo_df[['exercicio_fisico']].value_counts()

exercicio_fisico
Não Pratica Regularmente    2733
2 - 4h por semana            758
>= 6h por semana             481
4 - 6h por semana            440
< 2h por semana              380
Name: count, dtype: int64

## Qualidade do sono

In [ ]:
novo_df = pd.merge(novo_df, dataset[['person_key', 'Q132', 'Q133', 'Q134']], on='person_key', how='left')

In [ ]:
# PESOS -----------------------------------------------------------

# Q132 - Uso de medicamento para dormir:
# Sim: -1 (indica busca de solução para o problema)
# Não: 0

# Q133 - Número de dias usando medicamento para dormir:
# 1 a 3 dias: -1 (indica uso ocasional)
# 4 a 7 dias: -2 (indica uso frequente)
# 8 a 14 dias: -3 (indica uso crônico)

# Q134 - Medicamento prescrito por médico:
# Sim: -2 (indica busca de orientação profissional)
# Não: -1 (indica automedicação)

# ------------------------------------------------------------------

In [ ]:
novo_df.loc[
    (
        (novo_df[['Q132', 'Q134']] == 9).all(axis=1) & (novo_df['Q133'] == 99)
    ),
    'qualidade_sono'
] = 'Ignorado'

novo_df.loc[
    (
        novo_df[['Q132', 'Q133', 'Q134']].isnull().all(axis=1)
    ),
    'qualidade_sono'
] = 'Não Aplicável'

In [ ]:
novo_df['qualidade_sono'].fillna(0)

0       0
1       0
2       0
3       0
4       0
       ..
4787    0
4788    0
4789    0
4790    0
4791    0
Name: qualidade_sono, Length: 4792, dtype: int64

In [ ]:
# Precompute indices based on conditions
indice = 5
q133_indices = [0, 1, 2, 4, 5, 6, 8, 9, 10, 11, 12, 13]
q134_indices = [1, 2]

# Vectorized operations
novo_df['qualidade_sono'] = indice

# Condition for Q132
q132_condition = novo_df['Q132'] == 1
novo_df.loc[q132_condition, 'qualidade_sono'] -= 1

# Condition for Q133
novo_df.loc[q132_condition & novo_df['Q133'].isin(q133_indices), 'qualidade_sono'] -= 1
novo_df.loc[q132_condition & novo_df['Q133'].between(4, 7), 'qualidade_sono'] -= 2
novo_df.loc[q132_condition & novo_df['Q133'].between(8, 14), 'qualidade_sono'] -= 3

# Condition for Q134
novo_df.loc[q132_condition & novo_df['Q134'].isin(q134_indices), 'qualidade_sono'] -= 1

In [ ]:
novo_df[['Q132', 'Q133', 'Q134', 'qualidade_sono']]

      Q132  Q133  Q134  qualidade_sono
0        2   NaN   NaN               5
1        1  14.0   1.0               0
2        1   7.0   1.0               1
3        2   NaN   NaN               5
4        1   3.0   2.0               3
...    ...   ...   ...             ...
4787     2   NaN   NaN               5
4788     1   1.0   2.0               2
4789     2   NaN   NaN               5
4790     1   7.0   1.0               1
4791     2   NaN   NaN               5

[4792 rows x 4 columns]

In [ ]:
novo_df[['qualidade_sono']].value_counts(dropna=False)

qualidade_sono
 5                2998
 0                1166
 1                 257
 2                 231
 3                  83
-1                  57
Name: count, dtype: int64

In [ ]:
novo_df.drop(columns=['Q132', 'Q133', 'Q134'], inplace=True)

In [ ]:
novo_df.loc[novo_df['qualidade_sono'] == -1]

,person_key,sexo,idade,cor_raca,estado_civil,toc,violencia_psicologica,violencia_fisica,violencia_sexual,vulnerabilidade_trabalho,...,moradia,utilizacao_servicos_saude,plano_saude,doencas_cronicas,sofrimentos_mentais,ingestao_alcool,tabaco,frequencia_escovacao_dentaria,exercicio_fisico,qualidade_sono
36,11_1152011_110011130_15_2,Mulher,Idade Madura,Branca,Solteiro(a),Não,Não,Não,Não,Não,...,Habitação Não Saudável,6-10x por ano,0,Sim,Sim,Nunca,Nunca Fumou,3x ou mais por dia,Não Pratica Regularmente,-1
461,21_2140020_210016667_5_5,Mulher,Adulto,Parda,Solteiro(a),Não,Não,Não,Não,Sim,...,Habitação Não Saudável,6-10x por ano,0,Não,Sim,Nunca,"Já foi fumante, mas não fuma atualmente",1x por dia,Não Pratica Regularmente,-1
620,22_2220010_220032262_11_2,Mulher,Meia Idade,Parda,Divorciado(a) ou desquitado(a) ou separado(a) ...,Não,Sim,Não,Não,Sim,...,Habitação Não Saudável,11-15x por ano,0,Sim,Sim,Nunca,"Já foi fumante, mas não fuma atualmente",2x por dia,Não Pratica Regularmente,-1
638,22_2251021_220007508_11_3,Mulher,Adulto,Branca,Solteiro(a),Não,Sim,Não,Não,Sim,...,Habitação Não Saudável,1-5x por ano,0,Não,Sim,Nunca,"Já foi fumante, mas não fuma atualmente",3x ou mais por dia,Não Pratica Regularmente,-1
844,23_2353011_230037899_5_2,Homem,Meia Idade,Branca,Casado(a),Não,Não,Não,Não,Sim,...,Habitação Não Saudável,1-5x por ano,0,Não,Sim,Nunca,Nunca Fumou,2x por dia,Não Pratica Regularmente,-1
866,23_2353021_230075640_2_1,Homem,Idade Madura,Branca,Casado(a),Não,Sim,Sim,Não,Não,...,Habitação Não Saudável,6-10x por ano,1 ou mais,Sim,Sim,Nunca,"Já foi fumante, mas não fuma atualmente",2x por dia,< 2h por semana,-1
891,23_2354011_230123020_2_1,Homem,Meia Idade,Parda,Divorciado(a) ou desquitado(a) ou separado(a) ...,Não,Não,Não,Não,Sim,...,Habitação Não Saudável,1-5x por ano,0,Não,Sim,< 1x por semana,Nunca Fumou,3x ou mais por dia,Não Pratica Regularmente,-1
918,24_2410011_240004163_6_1,Mulher,Meia Idade,Parda,Casado(a),Não,Sim,Não,Não,Sim,...,Habitação Não Saudável,6-10x por ano,0,Sim,Sim,Nunca,Nunca Fumou,2x por dia,< 2h por semana,-1
1121,25_2510012_250067546_11_1,Mulher,Meia Idade,Parda,Solteiro(a),Não,Não,Não,Sim,Sim,...,Habitação Não Saudável,1-5x por ano,0,Sim,Sim,Nunca,Nunca Fumou,3x ou mais por dia,Não Pratica Regularmente,-1
1167,25_2552012_250003045_8_3,Homem,Meia Idade,Branca,Casado(a),Não,Não,Não,Não,Sim,...,Habitação Saudável,6-10x por ano,0,Sim,Sim,< 1x por semana,Nunca Fumou,2x por dia,Não Pratica Regularmente,-1
1184,25_2552013_250052121_2_1,Mulher,Meia Idade,Parda,Divorciado(a) ou desquitado(a) ou separado(a) ...,Não,Não,Não,Não,Não,...,Habitação Saudável,1-5x por ano,1 ou mais,Não,Sim,< 1x por semana,"Já foi fumante, mas não fuma atualmente",3x ou mais por dia,4 - 6h por semana,-1
1241,26_2610011_260016770_6_1,Homem,Meia Idade,Branca,Solteiro(a),Não,Não,Não,Não,Sim,...,Habitação Saudável,6-10x por ano,1 ou mais,Sim,Não,1-3x por semana,Nunca Fumou,2x por dia,>= 6h por semana,-1
1362,26_2651011_260076473_8_1,Mulher,Idade Madura,Branca,Viúvo(a),Não,Não,Não,Não,Não,...,Habitação Não Saudável,1-5x por ano,0,Sim,Sim,Nunca,Nunca Fumou,< 1x por dia,Não Pratica Regularmente,-1
1449,27_2710111_270006884_15_3,Mulher,Adulto,Parda,Casado(a),Não,Não,Não,Não,Sim,...,Habitação Saudável,1-5x por ano,0,Não,Não,Nunca,Nunca Fumou,3x ou mais por dia,Não Pratica Regularmente,-1
1569,28_2810011_280009911_5_1,Homem,Meia Idade,Parda,Casado(a),Não,Não,Não,Não,Não,...,Habitação Saudável,1-5x por ano,1 ou mais,Não,Sim,1-3x por semana,Nunca Fumou,3x ou mais por dia,Não Pratica Regularmente,-1
1583,28_2810011_280017440_13_1,Mulher,Meia Idade,Branca,Viúvo(a),Não,Não,Não,Não,Não,...,Habitação Saudável,1-5x por ano,1 ou mais,Sim,Sim,< 1x por semana,"Já foi fumante, mas não fuma atualmente",3x ou mais por dia,Não Pratica Regularmente,-1
1654,28_2820010_280033054_8_2,Mulher,Meia Idade,Parda,Solteiro(a),Não,Não,Não,Não,Sim,...,Habitação Não Saudável,1-5x por ano,0,Sim,Sim,Nunca,"Já foi fumante, mas não fuma atualmente",3x ou mais por dia,2 - 4h por semana,-1
1767,29_2910212_290031536_11_2,Mulher,Meia Idade,Parda,Casado(a),Não,Sim,Não,Sim,Sim,...,Habitação Saudável,6-10x por ano,0,Não,Sim,1-3x por semana,"Já foi fumante, mas não fuma atualmente",3x ou mais por dia,2 - 4h por semana,-1
1869,29_2955013_290068380_12_2,Mulher,Jovem Adulto,Parda,Solteiro(a),Não,Sim,Sim,Não,Sim,...,Habitação Não Saudável,1-5x por ano,1 ou mais,Sim,Sim,4-6x por semana,Nunca Fumou,3x ou mais por dia,Não Pratica Regularmente,-1
2080,31_3151013_310032653_5_1,Mulher,Idade Madura,Branca,Viúvo(a),Não,Sim,Não,Não,Não,...,Habitação Não Saudável,6-10x por ano,0,Sim,Sim,Nunca,Nunca Fumou,3x ou mais por dia,Não Pratica Regularmente,-1
2101,31_3152013_310062804_1_1,Mulher,Idade Madura,Parda,Divorciado(a) ou desquitado(a) ou separado(a) ...,Não,Não,Não,Não,Não,...,Habitação Saudável,6-10x por ano,1 ou mais,Sim,Não,Nunca,"Já foi fumante, mas não fuma atualmente",3x ou mais por dia,Não Pratica Regularmente,-1
2193,31_3156011_310117190_3_1,Mulher,Idade Madura,Branca,Casado(a),Não,Não,Não,Não,Sim,...,Habitação Não Saudável,1-5x por ano,1 ou mais,Sim,Sim,Nunca,Nunca Fumou,3x ou mais por dia,>= 6h por semana,-1
2236,31_3156022_310095014_10_1,Mulher,Idade Madura,Parda,Casado(a),Não,Não,Não,Não,Não,...,Habitação Não Saudável,6-10x por ano,0,Sim,Sim,Nunca,"Já foi fumante, mas não fuma atualmente",2x por dia,2 - 4h por semana,-1
2254,32_3210011_320023113_9_1,Mulher,Meia Idade,Preta,Solteiro(a),Não,Não,Não,Não,Sim,...,Habitação Não Saudável,1-5x por ano,0,Sim,Sim,1-3x por semana,Fuma diariamente,1x por dia,Não Pratica Regularmente,-1
2495,33_3310111_330228272_2_2,Homem,Idade Madura,Branca,Casado(a),Não,Não,Não,Não,Sim,...,Habitação Saudável,1-5x por ano,1 ou mais,Sim,Sim,4-6x por semana,Fuma diariamente,2x por dia,Não Pratica Regularmente,-1
2556,33_3310211_330312880_11_1,Mulher,Adulto,Parda,Solteiro(a),Não,Sim,Não,Não,Sim,...,Habitação Não Saudável,1-5x por ano,0,Sim,Sim,1-3x por semana,Fuma diariamente,3x ou mais por dia,Não Pratica Regularmente,-1
2590,33_3310311_330207521_8_1,Mulher,Idade Madura,Parda,Casado(a),Não,Não,Não,Sim,Não,...,Habitação Saudável,1-5x por ano,0,Sim,Sim,4-6x por semana,Fuma ocasionalmente,3x ou mais por dia,< 2h por semana,-1
2732,33_3353011_330287575_11_1,Mulher,Meia Idade,Preta,Divorciado(a) ou desquitado(a) ou separado(a) ...,Não,Sim,Não,Não,Não,...,Habitação Não Saudável,1-5x por ano,1 ou mais,Sim,Sim,Nunca,Fuma diariamente,2x por dia,Não Pratica Regularmente,-1
2788,35_3510111_350496959_9_1,Homem,Meia Idade,Branca,Casado(a),Não,Não,Não,Não,Não,...,Habitação Saudável,1-5x por ano,1 ou mais,Sim,Sim,1-3x por semana,Fuma diariamente,3x ou mais por dia,< 2h por semana,-1
2794,35_3510111_350558112_12_1,Homem,Meia Idade,Branca,Casado(a),Não,Não,Não,Sim,Não,...,Habitação Não Saudável,6-10x por ano,1 ou mais,Sim,Sim,Nunca,Nunca Fumou,3x ou mais por dia,2 - 4h por semana,-1
2913,35_3510311_350207240_10_1,Homem,Idade Madura,Branca,Casado(a),Não,Não,Não,Não,Não,...,Habitação Saudável,1-5x por ano,1 ou mais,Sim,Sim,Nunca,Nunca Fumou,2x por dia,4 - 6h por semana,-1
3145,35_3554011_350058860_10_2,Mulher,Adulto,Parda,Casado(a),Não,Sim,Não,Sim,Sim,...,Habitação Saudável,11-15x por ano,1 ou mais,Sim,Sim,Nunca,Nunca Fumou,3x ou mais por dia,Não Pratica Regularmente,-1
3260,41_4110212_410072201_3_1,Mulher,Adulto,Parda,Casado(a),Não,Não,Não,Não,Sim,...,Habitação Saudável,6-10x por ano,1 ou mais,Não,Sim,1-3x por semana,"Já foi fumante, mas não fuma atualmente",3x ou mais por dia,Não Pratica Regularmente,-1
3301,41_4120012_410190109_4_1,Mulher,Meia Idade,Branca,Casado(a),Não,Não,Não,Não,Sim,...,Habitação Não Saudável,11-15x por ano,1 ou mais,Sim,Sim,Nunca,Nunca Fumou,3x ou mais por dia,Não Pratica Regularmente,-1
3392,41_4155021_410038076_11_1,Mulher,Meia Idade,Parda,Divorciado(a) ou desquitado(a) ou separado(a) ...,Não,Sim,Não,Não,Sim,...,Habitação Não Saudável,6-10x por ano,0,Sim,Sim,Nunca,Nunca Fumou,3x ou mais por dia,>= 6h por semana,-1
3437,42_4210011_420041324_1_1,Mulher,Adulto,Branca,Solteiro(a),Não,Sim,Sim,Não,Não,...,Habitação Não Saudável,1-5x por ano,0,Não,Sim,1-3x por semana,"Já foi fumante, mas não fuma atualmente",3x ou mais por dia,>= 6h por semana,-1
3551,42_4252012_420009333_4_1,Mulher,Idade Madura,Parda,Divorciado(a) ou desquitado(a) ou separado(a) ...,Não,Sim,Não,Sim,Sim,...,Habitação Não Saudável,11-15x por ano,0,Sim,Sim,Nunca,"Já foi fumante, mas não fuma atualmente",3x ou mais por dia,Não Pratica Regularmente,-1
3604,42_4253012_420118097_10_1,Mulher,Meia Idade,Parda,Solteiro(a),Não,Sim,Não,Não,Sim,...,Habitação Saudável,< 1x por ano,0,Sim,Sim,Nunca,"Já foi fumante, mas não fuma atualmente",3x ou mais por dia,2 - 4h por semana,-1
3669,43_4310113_430023913_8_1,Mulher,Adulto,Branca,Casado(a),Não,Não,Não,Não,Sim,...,Habitação Saudável,6-10x por ano,1 ou mais,Não,Sim,1-3x por semana,Nunca Fumou,3x ou mais por dia,2 - 4h por semana,-1
3734,43_4310213_430012978_8_1,Mulher,Meia Idade,Branca,Solteiro(a),Não,Não,Não,Não,Sim,...,Habitação Não Saudável,1-5x por ano,0,Sim,Sim,Nunca,Fuma diariamente,2x por dia,Não Pratica Regularmente,-1
3768,43_4321011_430207454_3_1,Mulher,Jovem Adulto,Branca,Solteiro(a),Não,Não,Não,Não,Não,...,Habitação Não Saudável,1-5x por ano,1 ou mais,Sim,Sim,Nunca,Nunca Fumou,3x ou mais por dia,Não Pratica Regularmente,-1
3894,43_4355011_430169674_7_3,Mulher,Adulto,Branca,Casado(a),Não,Sim,Não,Não,Não,...,Habitação Saudável,6-10x por ano,1 ou mais,Sim,Sim,Nunca,"Já foi fumante, mas não fuma atualmente",2x por dia,Não Pratica Regularmente,-1
3953,50_5010011_500033340_15_3,Mulher,Jovem Adulto,Branca,Solteiro(a),Não,Sim,Não,Não,Sim,...,Habitação Saudável,1-5x por ano,1 ou mais,Não,Sim,1-3x por semana,Fuma diariamente,3x ou mais por dia,>= 6h por semana,-1
3979,50_5010012_500000613_13_2,Mulher,Adulto,Branca,Casado(a),Não,Não,Não,Não,Não,...,Habitação Saudável,1-5x por ano,1 ou mais,Sim,Sim,Nunca,Nunca Fumou,3x ou mais por dia,Não Pratica Regularmente,-1
3984,50_5010012_500008135_11_1,Mulher,Meia Idade,Branca,Solteiro(a),Não,Sim,Sim,Sim,Não,...,Habitação Saudável,1-5x por ano,1 ou mais,Não,Sim,1-3x por semana,Nunca Fumou,3x ou mais por dia,2 - 4h por semana,-1
4079,50_5052020_500019927_11_1,Homem,Idade Madura,Branca,Casado(a),Não,Não,Não,Não,Não,...,Habitação Não Saudável,1-5x por ano,0,Sim,Sim,< 1x por semana,"Já foi fumante, mas não fuma atualmente",2x por dia,Não Pratica Regularmente,-1
4084,50_5052020_500038490_13_2,Homem,Meia Idade,Parda,Solteiro(a),Não,Sim,Não,Não,Sim,...,Habitação Não Saudável,6-10x por ano,0,Sim,Sim,< 1x por semana,"Já foi fumante, mas não fuma atualmente",3x ou mais por dia,Não Pratica Regularmente,-1
4186,51_5153020_510004184_8_1,Homem,Idade Madura,Branca,Casado(a),Não,Não,Não,Não,Não,...,Habitação Não Saudável,1-5x por ano,0,Sim,Sim,1-3x por semana,"Já foi fumante, mas não fuma atualmente",2x por dia,Não Pratica Regularmente,-1
4267,52_5210013_520050541_7_1,Homem,Adulto,Parda,Casado(a),Não,Sim,Sim,Não,Não,...,Habitação Não Saudável,6-10x por ano,0,Não,Sim,Nunca,Nunca Fumou,2x por dia,4 - 6h por semana,-1
4278,52_5220012_520007680_1_3,Homem,Adulto,Parda,Solteiro(a),Não,Não,Não,Não,Sim,...,Habitação Não Saudável,6-10x por ano,0,Sim,Sim,Nunca,Nunca Fumou,3x ou mais por dia,Não Pratica Regularmente,-1
4320,52_5251012_520048553_14_1,Mulher,Meia Idade,Branca,Divorciado(a) ou desquitado(a) ou separado(a) ...,Não,Sim,Não,Não,Sim,...,Habitação Saudável,1-5x por ano,1 ou mais,Sim,Sim,< 1x por semana,Nunca Fumou,3x ou mais por dia,2 - 4h por semana,-1
4420,53_5310113_530007950_14_1,Homem,Adulto,Branca,Solteiro(a),Não,Sim,Sim,Sim,Não,...,Habitação Saudável,6-10x por ano,1 ou mais,Não,Sim,4-6x por semana,Nunca Fumou,3x ou mais por dia,< 2h por semana,-1
4444,53_5310211_530011761_7_2,Mulher,Meia Idade,Indígena,Solteiro(a),Não,Não,Não,Não,Sim,...,Habitação Saudável,1-5x por ano,0,Não,Sim,1-3x por semana,Fuma diariamente,3x ou mais por dia,Não Pratica Regularmente,-1
4500,11_1110012_110017590_6_1,Mulher,Meia Idade,Parda,Casado(a),Sim,Não,Não,Não,Não,...,Habitação Não Saudável,1-5x por ano,1 ou mais,Não,Sim,Nunca,Nunca Fumou,3x ou mais por dia,2 - 4h por semana,-1
4617,32_3210011_320008258_11_2,Mulher,Adulto,Parda,Casado(a),Sim,Não,Não,Não,Sim,...,Habitação Saudável,> 15x por ano,1 ou mais,Sim,Sim,Nunca,Nunca Fumou,3x ou mais por dia,Não Pratica Regularmente,-1
4627,32_3220012_320030310_4_1,Mulher,Meia Idade,Branca,Divorciado(a) ou desquitado(a) ou separado(a) ...,Sim,Sim,Não,Sim,Sim,...,Habitação Saudável,1-5x por ano,0,Não,Sim,1-3x por semana,Nunca Fumou,2x por dia,>= 6h por semana,-1
4757,51_5110011_510042597_8_1,Mulher,Adulto,Parda,Casado(a),Sim,Não,Não,Sim,Não,...,Habitação Saudável,1-5x por ano,1 ou mais,Sim,Sim,Nunca,Nunca Fumou,3x ou mais por dia,2 - 4h por semana,-1

In [ ]:
ruim_condition = (novo_df['qualidade_sono'] >= -1) & (novo_df['qualidade_sono'] <= 1)
moderado_condition = (novo_df['qualidade_sono'] >= 2) & (novo_df['qualidade_sono'] <= 4)
bom_condition = (novo_df['qualidade_sono'] == 5)

novo_df.loc[ruim_condition, 'qualidade_sono'] = 'Ruim'
novo_df.loc[moderado_condition, 'qualidade_sono'] = 'Moderado'
novo_df.loc[bom_condition, 'qualidade_sono'] = 'Bom'

In [ ]:
novo_df[['qualidade_sono']].value_counts()

qualidade_sono
Bom               2998
Ruim              1480
Moderado           314
Name: count, dtype: int64

## Uso de Telas

In [ ]:
novo_df = pd.merge(novo_df, dataset[['person_key', 'P04501', 'P04502']], on='person_key', how='left')

In [ ]:
# Replace 'Ignorado' where both P04501 and P04502 are 9
novo_df.loc[
    (novo_df[['P04501', 'P04502']] == 9).all(axis=1),
    'uso_telas'
] = 'Ignorado'

# Replace 'Não Aplicável' where both P04501 and P04502 are null
novo_df.loc[
    novo_df[['P04501', 'P04502']].isnull().all(axis=1),
    'uso_telas'
] = 'Não Aplicável'

# Replace 'Não Usa Telas' where both P04501 and P04502 are 6
novo_df.loc[
    (novo_df[['P04501', 'P04502']] == 6).all(axis=1),
    'uso_telas'
] = 0

# Replace values of P04501 where P04501 is 6 and less than 6 in the same row
novo_df.loc[
    ((novo_df['P04501'] == 6) & (novo_df['P04502'] < 6)),
    'uso_telas'
] = novo_df['P04502']

# Replace values of P04502 where P04502 is 6 and less than 6 in the same row
novo_df.loc[
    ((novo_df['P04502'] == 6) & (novo_df['P04501'] < 6)),
    'uso_telas'
] = novo_df['P04501']

# Replace null values in 'uso_telas' with the sum of P04501 and P04502
novo_df.loc[
    novo_df['uso_telas'].isnull(),
    'uso_telas'
] = novo_df['P04501'] + novo_df['P04502']

In [ ]:
novo_df[['uso_telas']].value_counts()

uso_telas
5            858
4            854
3            704
6            576
2            564
7            373
1            266
8            245
9            152
0            133
10            67
Name: count, dtype: int64

In [ ]:
ruim_condition = (novo_df['uso_telas'] > 5)
moderado_condition = (novo_df['uso_telas'] >= 3) & (novo_df['uso_telas'] <= 5)
bom_condition = (novo_df['uso_telas'] > 0) & (novo_df['uso_telas'] < 3)
muito_bom_condition = (novo_df['uso_telas'] == 0)

novo_df.loc[ruim_condition, 'uso_telas'] = 'Alto'
novo_df.loc[moderado_condition, 'uso_telas'] = 'Moderado'
novo_df.loc[bom_condition, 'uso_telas'] = 'Baixo'
novo_df.loc[muito_bom_condition, 'uso_telas'] = 'Não Usa Telas'

In [ ]:
novo_df.drop(columns=['P04501', 'P04502'], inplace=True)

In [ ]:
novo_df

,person_key,sexo,idade,cor_raca,estado_civil,toc,violencia_psicologica,violencia_fisica,violencia_sexual,vulnerabilidade_trabalho,...,utilizacao_servicos_saude,plano_saude,doencas_cronicas,sofrimentos_mentais,ingestao_alcool,tabaco,frequencia_escovacao_dentaria,exercicio_fisico,qualidade_sono,uso_telas
0,11_1110011_110003808_2_1,Mulher,Meia Idade,Preta,Solteiro(a),Não,Não,Não,Não,Sim,...,1-5x por ano,0,Sim,Sim,Nunca,"Já foi fumante, mas não fuma atualmente",1x por dia,Não Pratica Regularmente,Bom,Moderado
1,11_1110011_110003808_7_1,Mulher,Adulto,Branca,Casado(a),Não,Não,Não,Não,Sim,...,6-10x por ano,0,Sim,Sim,Nunca,Nunca Fumou,3x ou mais por dia,Não Pratica Regularmente,Ruim,Moderado
2,11_1110011_110007557_7_1,Mulher,Idade Madura,Branca,Solteiro(a),Não,Não,Não,Não,Sim,...,6-10x por ano,1 ou mais,Sim,Sim,Nunca,Nunca Fumou,3x ou mais por dia,Não Pratica Regularmente,Ruim,Alto
3,11_1110011_110008644_4_2,Homem,Jovem Adulto,Branca,Solteiro(a),Não,Não,Não,Não,Não,...,1-5x por ano,0,Não,Sim,Nunca,Fuma ocasionalmente,3x ou mais por dia,Não Pratica Regularmente,Bom,Moderado
4,11_1110011_110008644_15_1,Mulher,Idade Madura,Parda,Divorciado(a) ou desquitado(a) ou separado(a) ...,Não,Não,Não,Não,Não,...,6-10x por ano,0,Sim,Sim,Nunca,"Já foi fumante, mas não fuma atualmente",3x ou mais por dia,Não Pratica Regularmente,Moderado,Moderado
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4787,53_5310211_530000135_7_1,Mulher,Adulto,Parda,Solteiro(a),Sim,Não,Não,Sim,Sim,...,6-10x por ano,0,Não,Não,Nunca,Nunca Fumou,3x ou mais por dia,2 - 4h por semana,Bom,Alto
4788,53_5310211_530037460_2_1,Mulher,Meia Idade,Parda,Casado(a),Sim,Não,Não,Não,Não,...,6-10x por ano,1 ou mais,Sim,Sim,Nunca,Nunca Fumou,2x por dia,Não Pratica Regularmente,Moderado,Alto
4789,53_5310211_530042333_3_1,Mulher,Meia Idade,Parda,Divorciado(a) ou desquitado(a) ou separado(a) ...,Sim,Não,Não,Não,Não,...,6-10x por ano,0,Sim,Sim,Nunca,Nunca Fumou,2x por dia,Não Pratica Regularmente,Bom,Moderado
4790,53_5310212_530029819_15_1,Homem,Meia Idade,Preta,Solteiro(a),Sim,Sim,Não,Não,Sim,...,1-5x por ano,0,Sim,Sim,Nunca,Fuma diariamente,2x por dia,< 2h por semana,Ruim,Não Usa Telas
4791,53_5310212_530033471_9_2,Mulher,Meia Idade,Preta,Solteiro(a),Sim,Sim,Sim,Sim,Não,...,1-5x por ano,0,Sim,Sim,< 1x por semana,Fuma diariamente,2x por dia,2 - 4h por semana,Bom,Moderado

In [ ]:
novo_df[['uso_telas']].value_counts()

uso_telas
Moderado         2416
Alto             1413
Baixo             830
Não Usa Telas     133
Name: count, dtype: int64

## Qualidade Alimentação

In [ ]:
pesos = {
    'P006': 5,      # Feijão
    'P00901': 8,    # Verduras/Legumes
    'P01101': 4,    # Carne vermelha
    'P013': 4,      # Frango
    'P015': 4,      # Peixe
    'P023': 2,      # Leite
    'P01601': 3,    # Suco natural
    'P018': 4,      # Frutas
    'P02002': -5,   # Refrigerante
    'P02001': -4,   # Suco de caixinha
    'P02501': -8,   # Besteira
    'P02602': -8    # Lanche rápido
}

alimentos = [
    'P006',    # Feijão
    'P00901',  # Verduras/Legumes
    'P01101',  # Carne vermelha
    'P013',    # Frango
    'P015',    # Peixe
    'P023',    # Leite
    'P01601',  # Suco natural
    'P018',    # Frutas
    'P02002',  # Refrigerante
    'P02001',  # Suco de caixinha
    'P02501',  # Besteira
    'P02602'   # Lanche rápido
]

In [ ]:
alimentos_df = dataset[['person_key']+ alimentos].copy()

In [ ]:
unique_values = pd.concat([alimentos_df[col].value_counts() for col in alimentos]).index.unique()
unique_values

Index([7, 3, 2, 5, 0, 1, 4, 6], dtype='int64')

In [ ]:
for col, weight in pesos.items():
    alimentos_df[col] *= weight

soma_pesos = sum(pesos.values())


alimentos_df['qualidade_alimentacao_valores'] = (alimentos_df[alimentos].sum(axis=1) / soma_pesos)

In [ ]:
alimentos_df['qualidade_alimentacao_valores'].describe(percentiles=[0, 0.2, 0.3, 0.4, 0.8])

count    4792.000000
mean        9.944746
std         5.528662
min       -11.333333
0%        -11.333333
20%         5.333333
30%         7.333333
40%         8.888889
50%        10.444444
80%        14.777778
max        24.000000
Name: qualidade_alimentacao_valores, dtype: float64

In [ ]:
alimentos_df['qualidade_alimentacao'] = pd.qcut(alimentos_df['qualidade_alimentacao_valores'], q=4, labels=['Muito Ruim', 'Ruim', 'Moderada', 'Boa'])

In [ ]:
alimentos_df.groupby('qualidade_alimentacao')['qualidade_alimentacao_valores'].agg(['min', 'max']).reset_index()

  qualidade_alimentacao        min        max
0            Muito Ruim -11.333333   6.555556
1                  Ruim   6.666667  10.444444
2              Moderada  10.555556  14.000000
3                   Boa  14.111111  24.000000

In [ ]:
alimentos_df.loc[alimentos_df['qualidade_alimentacao'] == 'Boa']['qualidade_alimentacao_valores'].describe()

count    1187.000000
mean       16.545446
std         1.910452
min        14.111111
25%        15.000000
50%        16.111111
75%        17.722222
max        24.000000
Name: qualidade_alimentacao_valores, dtype: float64

In [ ]:
novo_df = pd.merge(novo_df, alimentos_df[['person_key', 'qualidade_alimentacao']], on='person_key', how='left')

In [ ]:
novo_df

,person_key,sexo,idade,cor_raca,estado_civil,toc,violencia_psicologica,violencia_fisica,violencia_sexual,vulnerabilidade_trabalho,...,plano_saude,doencas_cronicas,sofrimentos_mentais,ingestao_alcool,tabaco,frequencia_escovacao_dentaria,exercicio_fisico,qualidade_sono,uso_telas,qualidade_alimentacao
0,11_1110011_110003808_2_1,Mulher,Meia Idade,Preta,Solteiro(a),Não,Não,Não,Não,Sim,...,0,Sim,Sim,Nunca,"Já foi fumante, mas não fuma atualmente",1x por dia,Não Pratica Regularmente,Bom,Moderado,Muito Ruim
1,11_1110011_110003808_7_1,Mulher,Adulto,Branca,Casado(a),Não,Não,Não,Não,Sim,...,0,Sim,Sim,Nunca,Nunca Fumou,3x ou mais por dia,Não Pratica Regularmente,Ruim,Moderado,Moderada
2,11_1110011_110007557_7_1,Mulher,Idade Madura,Branca,Solteiro(a),Não,Não,Não,Não,Sim,...,1 ou mais,Sim,Sim,Nunca,Nunca Fumou,3x ou mais por dia,Não Pratica Regularmente,Ruim,Alto,Boa
3,11_1110011_110008644_4_2,Homem,Jovem Adulto,Branca,Solteiro(a),Não,Não,Não,Não,Não,...,0,Não,Sim,Nunca,Fuma ocasionalmente,3x ou mais por dia,Não Pratica Regularmente,Bom,Moderado,Boa
4,11_1110011_110008644_15_1,Mulher,Idade Madura,Parda,Divorciado(a) ou desquitado(a) ou separado(a) ...,Não,Não,Não,Não,Não,...,0,Sim,Sim,Nunca,"Já foi fumante, mas não fuma atualmente",3x ou mais por dia,Não Pratica Regularmente,Moderado,Moderado,Boa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4787,53_5310211_530000135_7_1,Mulher,Adulto,Parda,Solteiro(a),Sim,Não,Não,Sim,Sim,...,0,Não,Não,Nunca,Nunca Fumou,3x ou mais por dia,2 - 4h por semana,Bom,Alto,Boa
4788,53_5310211_530037460_2_1,Mulher,Meia Idade,Parda,Casado(a),Sim,Não,Não,Não,Não,...,1 ou mais,Sim,Sim,Nunca,Nunca Fumou,2x por dia,Não Pratica Regularmente,Moderado,Alto,Muito Ruim
4789,53_5310211_530042333_3_1,Mulher,Meia Idade,Parda,Divorciado(a) ou desquitado(a) ou separado(a) ...,Sim,Não,Não,Não,Não,...,0,Sim,Sim,Nunca,Nunca Fumou,2x por dia,Não Pratica Regularmente,Bom,Moderado,Moderada
4790,53_5310212_530029819_15_1,Homem,Meia Idade,Preta,Solteiro(a),Sim,Sim,Não,Não,Sim,...,0,Sim,Sim,Nunca,Fuma diariamente,2x por dia,< 2h por semana,Ruim,Não Usa Telas,Ruim
4791,53_5310212_530033471_9_2,Mulher,Meia Idade,Preta,Solteiro(a),Sim,Sim,Sim,Sim,Não,...,0,Sim,Sim,< 1x por semana,Fuma diariamente,2x por dia,2 - 4h por semana,Bom,Moderado,Moderada

## Medicamento Controlado

In [ ]:
medicamento = [
    'Q00503',
    'Q03303',
    'Q06508',
    'Q07211',
    'Q07212',
    'Q07601',
    'Q08609',
    # 'Q11406',
    'Q09606',
    'Q11806',
    'Q12607'
]

In [ ]:
novo_df = pd.merge(novo_df, dataset[['person_key'] + medicamento], on='person_key', how='left')

In [ ]:
novo_df.loc[
    (novo_df[medicamento] == 9).all(axis=1),
    'medicamento'
] = 'Ignorado'

novo_df.loc[
    novo_df[medicamento].isnull().all(axis=1),
    'medicamento'
] = 'Não Aplicável'

novo_df.loc[
    (~(novo_df[medicamento].eq(1).any(axis=1))) & (~(novo_df[medicamento].isnull().all(axis=1))),
    'medicamento'
] = 'Não faz uso de medicamento controlado'

novo_df.loc[
    (novo_df[medicamento]).eq(1).any(axis=1),
    'medicamento'
] =  'Faz uso de medicamento controlado'

In [ ]:
novo_df['medicamento'].value_counts(dropna=False)

medicamento
Faz uso de medicamento controlado        2790
Não Aplicável                            1232
Não faz uso de medicamento controlado     770
Name: count, dtype: int64

In [ ]:
novo_df = pd.merge(novo_df, dataset[['person_key', 'Q11406']], on='person_key', how='left')

In [ ]:
novo_df.loc[(novo_df['toc'] == 'Sim') & (novo_df['Q11406'] == 1) & (novo_df['medicamento'] == 'Não Aplicável')]['Q11406'].value_counts()

Q11406
1    24
Name: count, dtype: int64

In [ ]:
novo_df.loc[(novo_df['toc'] == 'Sim') & (novo_df['Q11406'] == 1) & (novo_df['medicamento'] == 'Não Aplicável'), 'medicamento'] = 'DROPAR'

In [ ]:
novo_df.loc[(novo_df['toc'] == 'Não') & (novo_df['Q11406'] == 1) & (novo_df['medicamento'] == 'Não Aplicável')]['Q11406'].value_counts()

Q11406
1    534
Name: count, dtype: int64

In [ ]:
novo_df.loc[(novo_df['toc'] == 'Não') & (novo_df['Q11406'] == 1) & (novo_df['medicamento'] == 'Não Aplicável'), 'medicamento'] = 'Faz uso de medicamento controlado'

In [ ]:
novo_df.loc[(novo_df['toc'] == 'Não') & (novo_df['Q11406'] == 2) & (novo_df['medicamento'] == 'Não Aplicável')]['Q11406'].value_counts()

Q11406
2    636
Name: count, dtype: int64

In [ ]:
novo_df.loc[(novo_df['toc'] == 'Sim') & (novo_df['Q11406'] == 2) & (novo_df['medicamento'] == 'Não Aplicável')]['Q11406'].value_counts()

Q11406
2    38
Name: count, dtype: int64

In [ ]:
novo_df.loc[(novo_df['Q11406'] == 2) & (novo_df['medicamento'] == 'Não Aplicável'), 'medicamento'] = 'Não faz uso de medicamento controlado'

In [ ]:
novo_df.drop(columns=medicamento+['Q11406'], inplace=True)

In [ ]:
novo_df[['medicamento']].value_counts()

medicamento
Faz uso de medicamento controlado        3324
Não faz uso de medicamento controlado    1444
DROPAR                                     24
Name: count, dtype: int64

In [ ]:
novo_df.drop(novo_df[novo_df['medicamento'] == 'DROPAR'].index, inplace=True)

In [ ]:
novo_df[['medicamento']].value_counts()

medicamento
Faz uso de medicamento controlado        3324
Não faz uso de medicamento controlado    1444
Name: count, dtype: int64

In [ ]:
novo_df

,person_key,sexo,idade,cor_raca,estado_civil,toc,violencia_psicologica,violencia_fisica,violencia_sexual,vulnerabilidade_trabalho,...,doencas_cronicas,sofrimentos_mentais,ingestao_alcool,tabaco,frequencia_escovacao_dentaria,exercicio_fisico,qualidade_sono,uso_telas,qualidade_alimentacao,medicamento
0,11_1110011_110003808_2_1,Mulher,Meia Idade,Preta,Solteiro(a),Não,Não,Não,Não,Sim,...,Sim,Sim,Nunca,"Já foi fumante, mas não fuma atualmente",1x por dia,Não Pratica Regularmente,Bom,Moderado,Muito Ruim,Faz uso de medicamento controlado
1,11_1110011_110003808_7_1,Mulher,Adulto,Branca,Casado(a),Não,Não,Não,Não,Sim,...,Sim,Sim,Nunca,Nunca Fumou,3x ou mais por dia,Não Pratica Regularmente,Ruim,Moderado,Moderada,Faz uso de medicamento controlado
2,11_1110011_110007557_7_1,Mulher,Idade Madura,Branca,Solteiro(a),Não,Não,Não,Não,Sim,...,Sim,Sim,Nunca,Nunca Fumou,3x ou mais por dia,Não Pratica Regularmente,Ruim,Alto,Boa,Faz uso de medicamento controlado
3,11_1110011_110008644_4_2,Homem,Jovem Adulto,Branca,Solteiro(a),Não,Não,Não,Não,Não,...,Não,Sim,Nunca,Fuma ocasionalmente,3x ou mais por dia,Não Pratica Regularmente,Bom,Moderado,Boa,Não faz uso de medicamento controlado
4,11_1110011_110008644_15_1,Mulher,Idade Madura,Parda,Divorciado(a) ou desquitado(a) ou separado(a) ...,Não,Não,Não,Não,Não,...,Sim,Sim,Nunca,"Já foi fumante, mas não fuma atualmente",3x ou mais por dia,Não Pratica Regularmente,Moderado,Moderado,Boa,Faz uso de medicamento controlado
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4785,53_5310113_530004453_11_3,Mulher,Meia Idade,Branca,Solteiro(a),Sim,Não,Não,Não,Não,...,Sim,Sim,1-3x por semana,Nunca Fumou,2x por dia,Não Pratica Regularmente,Moderado,Moderado,Moderada,Faz uso de medicamento controlado
4786,53_5310113_530010691_14_1,Mulher,Adulto,Parda,Divorciado(a) ou desquitado(a) ou separado(a) ...,Sim,Sim,Não,Não,Não,...,Não,Sim,< 1x por semana,Nunca Fumou,3x ou mais por dia,4 - 6h por semana,Bom,Moderado,Moderada,Não faz uso de medicamento controlado
4788,53_5310211_530037460_2_1,Mulher,Meia Idade,Parda,Casado(a),Sim,Não,Não,Não,Não,...,Sim,Sim,Nunca,Nunca Fumou,2x por dia,Não Pratica Regularmente,Moderado,Alto,Muito Ruim,Faz uso de medicamento controlado
4790,53_5310212_530029819_15_1,Homem,Meia Idade,Preta,Solteiro(a),Sim,Sim,Não,Não,Sim,...,Sim,Sim,Nunca,Fuma diariamente,2x por dia,< 2h por semana,Ruim,Não Usa Telas,Ruim,Faz uso de medicamento controlado
4791,53_5310212_530033471_9_2,Mulher,Meia Idade,Preta,Solteiro(a),Sim,Sim,Sim,Sim,Não,...,Sim,Sim,< 1x por semana,Fuma diariamente,2x por dia,2 - 4h por semana,Bom,Moderado,Moderada,Não faz uso de medicamento controlado

# FIM

In [ ]:
# novo_df = pd.merge(novo_df, dataset[['person_key', 'toc']], on='person_key', how='left')

In [ ]:
novo_df.loc[novo_df[novo_df.columns].isnull().all(axis=1)]

Empty DataFrame
Columns: [person_key, sexo, idade, cor_raca, estado_civil, toc, violencia_psicologica, violencia_fisica, violencia_sexual, vulnerabilidade_trabalho, nivel_instrucao, moradia, utilizacao_servicos_saude, plano_saude, doencas_cronicas, sofrimentos_mentais, ingestao_alcool, tabaco, frequencia_escovacao_dentaria, exercicio_fisico, qualidade_sono, uso_telas, qualidade_alimentacao, medicamento]
Index: []

[0 rows x 24 columns]

In [ ]:
novo_df.loc[novo_df[novo_df.columns].eq('Não Aplicável').any(axis=1)]

Empty DataFrame
Columns: [person_key, sexo, idade, cor_raca, estado_civil, toc, violencia_psicologica, violencia_fisica, violencia_sexual, vulnerabilidade_trabalho, nivel_instrucao, moradia, utilizacao_servicos_saude, plano_saude, doencas_cronicas, sofrimentos_mentais, ingestao_alcool, tabaco, frequencia_escovacao_dentaria, exercicio_fisico, qualidade_sono, uso_telas, qualidade_alimentacao, medicamento]
Index: []

[0 rows x 24 columns]

In [ ]:
novo_df.loc[novo_df[novo_df.columns].eq('Ignorado').any(axis=1)]

Empty DataFrame
Columns: [person_key, sexo, idade, cor_raca, estado_civil, toc, violencia_psicologica, violencia_fisica, violencia_sexual, vulnerabilidade_trabalho, nivel_instrucao, moradia, utilizacao_servicos_saude, plano_saude, doencas_cronicas, sofrimentos_mentais, ingestao_alcool, tabaco, frequencia_escovacao_dentaria, exercicio_fisico, qualidade_sono, uso_telas, qualidade_alimentacao, medicamento]
Index: []

[0 rows x 24 columns]

In [ ]:
novo_df.shape

(4768, 24)

In [ ]:
novo_df.loc[novo_df['toc'] == 'Sim'][['idade']].describe(percentiles=[])

             idade
count          270
unique           5
top     Meia Idade
freq           127

In [ ]:
novo_df.loc[novo_df['toc'] == 'Não'][['idade']].describe(percentiles=[])

             idade
count         4498
unique           5
top     Meia Idade
freq          1851

## Send to CSV

In [ ]:
novo_df.drop(columns=['person_key'], inplace = True)

In [ ]:
import random
# seed = random.randint(0, 100)
seed = 86

# Supondo que 'df' seja o seu DataFrame
# Subdividindo o DataFrame com base nos valores da classe 'toc'
toc_sim = novo_df[novo_df['toc'] == 'Sim']
toc_nao = novo_df[novo_df['toc'] == 'Não']

# Amostrando aleatoriamente o mesmo número de instâncias de cada subconjunto
num_amostras = min(len(toc_sim), len(toc_nao))
toc_nao_amostrado = toc_nao.sample(n=num_amostras+100, random_state=seed)

# Concatenando os subconjuntos amostrados em um novo DataFrame balanceado
df_balanceado = pd.concat([toc_sim, toc_nao_amostrado])

# Embaralhando as linhas, se desejar
df_balanceado = df_balanceado.sample(frac=1, random_state=seed).reset_index(drop=True)

In [ ]:
toc_nao

,sexo,idade,cor_raca,estado_civil,toc,violencia_psicologica,violencia_fisica,violencia_sexual,vulnerabilidade_trabalho,nivel_instrucao,...,doencas_cronicas,sofrimentos_mentais,ingestao_alcool,tabaco,frequencia_escovacao_dentaria,exercicio_fisico,qualidade_sono,uso_telas,qualidade_alimentacao,medicamento
0,Mulher,Meia Idade,Preta,Solteiro(a),Não,Não,Não,Não,Sim,Médio completo ou equivalente,...,Sim,Sim,Nunca,"Já foi fumante, mas não fuma atualmente",1x por dia,Não Pratica Regularmente,Bom,Moderado,Muito Ruim,Faz uso de medicamento controlado
1,Mulher,Adulto,Branca,Casado(a),Não,Não,Não,Não,Sim,Superior incompleto ou equivalente,...,Sim,Sim,Nunca,Nunca Fumou,3x ou mais por dia,Não Pratica Regularmente,Ruim,Moderado,Moderada,Faz uso de medicamento controlado
2,Mulher,Idade Madura,Branca,Solteiro(a),Não,Não,Não,Não,Sim,Superior completo,...,Sim,Sim,Nunca,Nunca Fumou,3x ou mais por dia,Não Pratica Regularmente,Ruim,Alto,Boa,Faz uso de medicamento controlado
3,Homem,Jovem Adulto,Branca,Solteiro(a),Não,Não,Não,Não,Não,Médio completo ou equivalente,...,Não,Sim,Nunca,Fuma ocasionalmente,3x ou mais por dia,Não Pratica Regularmente,Bom,Moderado,Boa,Não faz uso de medicamento controlado
4,Mulher,Idade Madura,Parda,Divorciado(a) ou desquitado(a) ou separado(a) ...,Não,Não,Não,Não,Não,Fundamental incompleto ou equivalente,...,Sim,Sim,Nunca,"Já foi fumante, mas não fuma atualmente",3x ou mais por dia,Não Pratica Regularmente,Moderado,Moderado,Boa,Faz uso de medicamento controlado
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4493,Homem,Meia Idade,Branca,Solteiro(a),Não,Não,Não,Não,Não,Sem instrução,...,Sim,Sim,Nunca,Nunca Fumou,< 1x por dia,Não Pratica Regularmente,Ruim,Não Usa Telas,Boa,Não faz uso de medicamento controlado
4494,Homem,Adulto,Parda,Casado(a),Não,Sim,Sim,Não,Sim,Médio completo ou equivalente,...,Sim,Sim,Nunca,"Já foi fumante, mas não fuma atualmente",2x por dia,Não Pratica Regularmente,Bom,Alto,Boa,Não faz uso de medicamento controlado
4495,Homem,Adulto,Parda,Solteiro(a),Não,Não,Não,Não,Sim,Médio incompleto ou equivalente,...,Sim,Sim,1-3x por semana,Nunca Fumou,3x ou mais por dia,>= 6h por semana,Bom,Alto,Ruim,Faz uso de medicamento controlado
4496,Mulher,Meia Idade,Branca,Solteiro(a),Não,Sim,Não,Sim,Sim,Médio incompleto ou equivalente,...,Sim,Sim,1-3x por semana,Nunca Fumou,1x por dia,Não Pratica Regularmente,Ruim,Moderado,Moderada,Faz uso de medicamento controlado
4497,Homem,Meia Idade,Parda,Casado(a),Não,Sim,Não,Não,Não,Médio completo ou equivalente,...,Não,Sim,Nunca,Nunca Fumou,3x ou mais por dia,2 - 4h por semana,Bom,Baixo,Ruim,Faz uso de medicamento controlado

In [ ]:
df_balanceado.to_csv('/content/drive/MyDrive/TCC - Identificação do Perfil de Pessoas com TOC no Brasil/Dados/vs_final_dataset_seed'+str(seed)+'.csv', index=False)

In [ ]:
df_balanceado.columns

Index(['sexo', 'idade', 'cor_raca', 'estado_civil', 'toc',
       'violencia_psicologica', 'violencia_fisica', 'violencia_sexual',
       'vulnerabilidade_trabalho', 'nivel_instrucao', 'moradia',
       'utilizacao_servicos_saude', 'plano_saude', 'doencas_cronicas',
       'sofrimentos_mentais', 'ingestao_alcool', 'tabaco',
       'frequencia_escovacao_dentaria', 'exercicio_fisico', 'qualidade_sono',
       'uso_telas', 'qualidade_alimentacao', 'medicamento'],
      dtype='object')

In [ ]:
df_balanceado['toc'].value_counts()

toc
Não    370
Sim    270
Name: count, dtype: int64

In [ ]:
seed

86